#!/bin/sh
# GNU gnulib localizations.
# This file is in the public domain.
#
# Script for regenerating all autogenerated files.

autopoint -f
rm po/Makevars.template
rm po/Rules-quot
rm po/boldquot.sed
rm po/en@boldquot.header
rm po/en@quot.header
rm po/insert-header.sed
rm po/quot.sed

aclocal -I m4
autoconf
automake --add-missing --copy
rm -rf autom4te.cache
