/* DO NOT EDIT! GENERATED AUTOMATICALLY! */
/* Categories of Unicode characters.  */
/* Generated automatically by gen-uni-tables.c for Unicode 15.0.0.  */

/* Copyright (C) 2000-2022 Free Software Foundation, Inc.

   This file is free software.
   It is dual-licensed under "the GNU LGPLv3+ or the GNU GPLv2+".
   You can redistribute it and/or modify it under either
     - the terms of the GNU Lesser General Public License as published
       by the Free Software Foundation, either version 3, or (at your
       option) any later version, or
     - the terms of the GNU General Public License as published by the
       Free Software Foundation; either version 2, or (at your option)
       any later version, or
     - the same dual license "the GNU LGPLv3+ or the GNU GPLv2+".

   This file is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Lesser General Public License and the GNU General Public License
   for more details.

   You should have received a copy of the GNU Lesser General Public
   License and of the GNU General Public License along with this
   program.  If not, see <https://www.gnu.org/licenses/>.  */

#define header_0 16
#define header_2 9
#define header_3 127
#define header_4 15
static const
struct
  {
    int header[1];
    int level1[17];
    short level2[2 << 7];
    unsigned int level3[3 << 4];
  }
u_categ_Co =
{
  { 17 },
  {
       18 * sizeof (int) / sizeof (short) +     0,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       18 * sizeof (int) / sizeof (short) +   128,
       18 * sizeof (int) / sizeof (short) +   128
  },
  {
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       -1,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +    16,
       -1,
       -1,
       -1,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +     0,
       18 +   256 * sizeof (short) / sizeof (int) +    32
  },
  {
    0xFFFFFFFFU, 0xFFFFFFFFU, 0xFFFFFFFFU, 0xFFFFFFFFU,
    0xFFFFFFFFU, 0xFFFFFFFFU, 0xFFFFFFFFU, 0xFFFFFFFFU,
    0xFFFFFFFFU, 0xFFFFFFFFU, 0xFFFFFFFFU, 0xFFFFFFFFU,
    0xFFFFFFFFU, 0xFFFFFFFFU, 0xFFFFFFFFU, 0xFFFFFFFFU,
    0xFFFFFFFFU, 0xFFFFFFFFU, 0xFFFFFFFFU, 0xFFFFFFFFU,
    0xFFFFFFFFU, 0xFFFFFFFFU, 0xFFFFFFFFU, 0xFFFFFFFFU,
    0x00000000U, 0x00000000U, 0x00000000U, 0x00000000U,
    0x00000000U, 0x00000000U, 0x00000000U, 0x00000000U,
    0xFFFFFFFFU, 0xFFFFFFFFU, 0xFFFFFFFFU, 0xFFFFFFFFU,
    0xFFFFFFFFU, 0xFFFFFFFFU, 0xFFFFFFFFU, 0xFFFFFFFFU,
    0xFFFFFFFFU, 0xFFFFFFFFU, 0xFFFFFFFFU, 0xFFFFFFFFU,
    0xFFFFFFFFU, 0xFFFFFFFFU, 0xFFFFFFFFU, 0x3FFFFFFFU
  }
};
