@node bcopy
@section @code{bcopy}
@findex bcopy

Removed in POSIX.1-2008.
POSIX.1-2004 specification: @url{https://pubs.opengroup.org/onlinepubs/009695399/functions/bcopy.html}

Gnulib module: bcopy
@mindex bcopy

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
mingw, MSVC 14, Android 9.0.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is removed in POSIX.1-2008.  Better use @code{memcpy}
or @code{memmove} instead.
@item
This module does not arrange to declare this function.
@end itemize
