@node bcopy
@section @code{bcopy}
@findex bcopy

POSIX specification: @url{https://pubs.opengroup.org/onlinepubs/009695399/functions/bcopy.html}

Gnulib module: bcopy

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
mingw, MSVC 14, Android 9.0.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is marked as ``legacy'' in POSIX@.  Better use @code{memcpy}
or @code{memmove} instead.
@end itemize
