@node ftime
@section @code{ftime}
@findex ftime

POSIX specification: @url{http://www.opengroup.org/susv3xsh/ftime.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Mac OS X 10.5, FreeBSD 6.0, NetBSD 5.0, OpenBSD 3.8, IRIX 5.3, Solaris 2.4.
@item
This function is marked as ``legacy'' in POSIX.  Better use @code{gettimeofday}
or @code{clock_gettime} instead, and use @code{ftime} only as a fallback for
portability to Windows platforms.
@end itemize
