@node ftw
@section @code{ftw}
@findex ftw

Removed in POSIX.1-2024.
POSIX.1-2017 specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/ftw.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@item
On platforms where @code{off_t} is a 32-bit type, this function may not
work correctly on files 2 GiB and larger.  @xref{Large File Support}.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
FreeBSD 5.2.1, NetBSD 3.0, Minix 3.1.8, mingw, MSVC 14, Android 4.1.
@item
This function is removed in POSIX.1-2024.
@mindex fts
Use the Gnulib module @code{fts} instead.
@end itemize
