@node h_errno
@section @code{h_errno}
@findex h_errno

POSIX specification: @url{https://pubs.opengroup.org/onlinepubs/009695399/functions/h_errno.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
glibc 2.34, IRIX 6.5, Cygwin 2.9, mingw, MSVC 14, Android 9.0.
@end itemize
