@node h_errno
@section @code{h_errno}
@findex h_errno

POSIX specification: @url{http://www.opengroup.org/susv3xsh/h_errno.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
IRIX 6.5, OSF/1 5.1, Cygwin, mingw, MSVC 9, Interix 3.5.
@end itemize
