@node index
@section @code{index}
@findex index

POSIX specification: @url{http://www.opengroup.org/susv3xsh/index.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Solaris 2.4, mingw, MSVC 9.
@item
This function is marked as ``legacy'' in POSIX.  Better use @code{strchr}
instead.
@end itemize
