@node mktemp
@section @code{mktemp}
@findex mktemp

Removed in POSIX.1-2008.
POSIX.1-2004 specification: @url{https://pubs.opengroup.org/onlinepubs/009695399/functions/mktemp.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is not appropriate for creating temporary files.  (It has
security risks.)  Therefore it is removed in POSIX.1-2008.  Better use
@code{mkstemp} instead.
@end itemize
