@node scalb
@section @code{scalb}
@findex scalb

Removed in POSIX.1-2008.
POSIX.1-2004 specification: @url{https://pubs.opengroup.org/onlinepubs/009695399/functions/scalb.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
