@node sigset
@section @code{sigset}
@findex sigset

Removed in POSIX.1-2024.
POSIX.1-2017 specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/sigset.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
FreeBSD 6.0, OpenBSD 7.5, Minix 3.1.8, Cygwin 1.5.x, mingw, MSVC 14, Android 7.1.
@item
This function is removed in POSIX.1-2024.
Use the function @code{sigaction} instead.
@end itemize
