@node usleep
@section @code{usleep}
@findex usleep

POSIX specification: @url{http://www.opengroup.org/susv3xsh/usleep.html}

Gnulib module: usleep

Portability problems fixed by Gnulib:
@itemize
@item
On some systems, @code{usleep} rejects attempts to sleep longer than 1
second, as allowed by POSIX:
mingw.
@item
This function is missing on some platforms.  However, the replacement
is designed to be lightweight, and may round to the nearest second;
use @code{select} or @code{nanosleep} if better resolution is needed:
IRIX 5.3, Solaris 2.4, older mingw, MSVC 9, BeOS.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
According to POSIX, the @code{usleep} function may interfere with the program's
use of the @code{SIGALRM} signal.  On Linux, it doesn't; on other platforms,
it may.
@end itemize
