@node utime
@section @code{utime}
@findex utime

Removed in POSIX.1-2024.
POSIX.1-2017 specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/utime.html}

Gnulib module: utime
@mindex utime

Portability problems fixed by Gnulib:
@itemize
@item
The times that are set on the file are affected by the current time zone and
by the DST flag of the current time zone on some platforms:
mingw, MSVC 14 (when the environment variable @env{TZ} is set).
@item
On some platforms, the prototype for @code{utime} omits @code{const}
for the second argument:
mingw, MSVC 14.
@item
On some platforms, @code{utime("link-to-file/",buf)} succeeds instead
of failing with @code{ENOTDIR}.
macOS 14.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
On some platforms, this function mis-handles a trailing slash:
Solaris 9.
@item
This function cannot set full timestamp resolution.
@mindex utimens
Use @code{utimensat(AT_FDCWD,file,times,0)},
or the gnulib module @code{utimens},
instead.
@item
This function sets a slightly different time stamp than the requested one:
@c https://dev.haiku-os.org/ticket/19215
Haiku.
@item
This function is removed in POSIX.1-2024.
You can use Gnulib module @code{utimens} instead.
@end itemize
