@node vfork
@section @code{vfork}
@findex vfork

POSIX specification: @url{http://www.opengroup.org/susv3xsh/vfork.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
IRIX 6.5, mingw, MSVC 9, BeOS.
@end itemize
