@node wcswcs
@section @code{wcswcs}
@findex wcswcs

POSIX specification: @url{https://pubs.opengroup.org/onlinepubs/009695399/functions/wcswcs.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
macOS 11.1, FreeBSD 13.0, Cygwin 2.9, mingw, MSVC 14, Android 9.0.
@item
On Windows and 32-bit AIX platforms, @code{wchar_t} is a 16-bit type and therefore cannot
accommodate all Unicode characters.
@item
This function is marked as ``legacy'' in POSIX@.  Better use @code{wcsstr}
instead.
@end itemize
