@node fcntl.h
@section @file{fcntl.h}

POSIX specification: @url{http://www.opengroup.org/susv3xbd/fcntl.h.html}

Gnulib module: fcntl-h

Portability problems fixed by Gnulib:
@itemize
@item
@samp{O_NOCTTY}, @samp{O_DSYNC}, @samp{O_NONBLOCK}, @samp{O_RSYNC},
@samp{O_SYNC}, @samp{O_DIRECTORY}, @samp{O_NOFOLLOW}, and
@samp{O_TTY_INIT} are not defined on some platforms.

@item
@samp{O_BINARY}, @samp{O_TEXT} (not specified by POSIX, but essential for
portability to Woe32 platforms) are defined on some platforms but not on
others.

@item
@samp{O_DIRECT}, @samp{O_NDELAY}, @samp{O_NOATIME},
and @samp{O_NOLINKS} (not specified by POSIX) are defined
on some platforms but not on others.

@item
@samp{FD_CLOEXEC} is not defined on some platforms:
mingw

@item
@samp{AT_FDCWD} is defined with a value too large for an int on some
platforms:
Solaris 10

@item
@samp{AT_FDCWD}, @samp{AT_SYMLINK_NOFOLLOW}, and @samp{AT_REMOVEDIR}
are missing on some platforms.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
@samp{O_CLOEXEC} is not defined on some platforms.  The gnulib
replacement is not atomic on these platforms.

@item
@samp{O_SEARCH} and @samp{O_EXEC} are not defined
on some platforms.

@item
@samp{F_DUPFD}, @samp{F_DUPFD_CLOEXEC}, @samp{F_GETFD}, and
@samp{F_SETFD} are not defined on some platforms:
mingw

@item
@samp{F_GETFL}, @samp{F_SETFL}, @samp{F_GETLK}, @samp{F_SETLK},
@samp{F_SETLOKW}, @samp{F_GETOWN}, and @samp{F_SETOWN} are not defined
on some platforms.

@item
@samp{POSIX_FADV_DONTNEED}, @samp{POSIX_FADV_NOREUSE},
@samp{POSIX_FADV_NORMAL}, @samp{POSIX_FADV_RANDOM},
@samp{POSIX_FADV_SEQUENTIAL}, and @samp{POSIX_FADV_WILLNEED} are not
defined on some platforms.

@item
@samp{AT_EACCESS} and @samp{AT_SYMLINK_FOLLOW} are missing on some platforms.
@end itemize
