@node inttypes.h
@section @file{inttypes.h}

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9799919799/basedefs/inttypes.h.html}

Gnulib module: inttypes-h
@mindex inttypes-h

Portability problems fixed by Gnulib:
@itemize
@item
This header file is missing on some platforms:
MSVC 9.
@item
This header file is very incomplete on some platforms.
@item
The declarations of @code{imaxabs} and @code{imaxdiv} are missing on some
platforms:
NetBSD 3.0, OpenBSD 3.8, AIX 5.1, HP-UX 11.
@item
The declarations of @code{strtoimax} and @code{strtoumax} are missing on some
platforms:
OpenBSD 3.8, AIX 5.1 (missing only @code{strtoumax}).
@item
On some hosts that predate C++11, when using C++ one must define
@code{__STDC_FORMAT_MACROS} to make visible the declarations of format
macros such as @code{PRIdMAX}.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
The macros @code{SCN*8}, @code{SCN*LEAST8}, @code{SCN*FAST8}
are missing on some platforms:
mingw without @code{__USE_MINGW_ANSI_STDIO}.
@item
The macros @code{PRIb*}, @code{PRIB*}, @code{SCNb*},
that were added in ISO C 23,
are missing on many platforms:
glibc 2.37 and many others.
@end itemize
