@node langinfo.h
@section @file{langinfo.h}

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/langinfo.h.html}

Gnulib module: langinfo

Portability problems fixed by Gnulib:
@itemize
@item
This header file is missing on some platforms:
Minix 3.1.8, mingw, MSVC 14.
@item
The constant @code{CODESET} is not defined on some platforms:
OpenBSD 6.7.
@item
The constants @code{ALTMON_1} to @code{ALTMON_12} are not defined on some
platforms:
glibc 2.26, musl libc, macOS 11.1, NetBSD 8.0, OpenBSD 6.5, AIX 7.2, HP-UX 11.31, IRIX 6.5, Solaris 11.4, Haiku, Cygwin 2.9.
@item
The constants @code{ERA}, @code{ERA_D_FMT}, @code{ERA_D_T_FMT},
@code{ERA_T_FMT}, @code{ALT_DIGITS} are not defined on some platforms:
OpenBSD 6.7.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
