@node locale.h
@section @file{locale.h}

POSIX specification:@* @url{http://www.opengroup.org/onlinepubs/9699919799/basedefs/locale.h.html}

Gnulib module: locale

Portability problems fixed by Gnulib:
@itemize
@item
The definition of @samp{LC_MESSAGES} is missing on some platforms:
mingw, MSVC 9.

@item
The @code{locale_t} type is not defined on some platforms:
glibc 2.11, MacOS X 10.5.

@item
Some platforms provide a @code{NULL} macro that cannot be used in arbitrary
expressions:
NetBSD 5.0
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
