@node math.h
@section @file{math.h}

POSIX specification: @url{http://www.opengroup.org/susv3xbd/math.h.html}

Gnulib module: math

Portability problems fixed by Gnulib:
@itemize
@item
The macro @code{NAN} is not defined on some platforms:
OpenBSD 4.0, AIX 5.1, IRIX 6.5, OSF/1 5.1, Solaris 10.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
@code{NAN} is not a compile time constant with some compilers:
OSF/1 with Compaq (ex-DEC) C 6.4.
@end itemize
