@node netdb.h
@section @file{netdb.h}

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/netdb.h.html}

Gnulib module: netdb

Portability problems fixed by Gnulib:
@itemize
@item
This header file is missing on some platforms:
mingw, MSVC 14.

@item
This header file is incomplete on some platforms:
Cygwin 1.5.x, Haiku.

@item
This header file does not define the type @code{socklen_t} on some platforms:
IRIX 6.5.

@item
This header file does not define @code{AI_ALL}, @code{AI_V4MAPPED}
on some platforms:
NetBSD 9.0.

@item
This header file does not define @code{AI_ADDRCONFIG} on some platforms:
NetBSD 5.0.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
