@node poll.h
@section @file{poll.h}

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9799919799/basedefs/poll.h.html}

Gnulib module: poll-h
@mindex poll-h

Portability problems fixed by Gnulib:
@itemize
@item
This header file is missing on some platforms:
mingw, MSVC 14.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
POSIX.1-2024 allows, but does not require, this file to make visible
all symbols from the headers @code{<signal.h>} and @code{<time.h>}.
Programs should not assume that these other symbols are visible merely
because this file is included, or that they are invisible because only
this file is included.
@end itemize
