@node sched.h
@section @file{sched.h}

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/sched.h.html}

Gnulib module: sched

Portability problems fixed by Gnulib:
@itemize
@item
This header file is missing on some platforms:
Minix 3.1.8, mingw, MSVC 14.
@item
This header file does not define the type @code{pid_t} on some platforms:
glibc 2.11, macOS 11.1.
@item
@code{struct sched_param} is not defined on some platforms:
Haiku.
@item
@code{SCHED_FIFO}, @code{SCHED_RR}, @code{SCHED_OTHER} are not defined on
some platforms:
Haiku.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
