@node sched.h
@section @file{sched.h}

POSIX specification: @url{http://www.opengroup.org/susv3xbd/sched.h.html}

Gnulib module: sched

Portability problems fixed by Gnulib:
@itemize
@item
This header file is missing on some platforms:
mingw, BeOS.
@item
@code{struct sched_param} is not defined on some platforms:
Haiku.
@item
@code{SCHED_FIFO}, @code{SCHED_RR}, @code{SCHED_OTHER} are not defined on
some platforms:
Haiku.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
