@node stdio.h
@section @file{stdio.h}

POSIX specification: @url{http://www.opengroup.org/susv3xbd/stdio.h.html}

Gnulib module: stdio

Portability problems fixed by Gnulib:
@itemize
@item
Some platforms provide a @code{NULL} macro that cannot be used in arbitrary
expressions:
NetBSD 5.0
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
