@node stdlib.h
@section @file{stdlib.h}

POSIX specification: @url{http://www.opengroup.org/susv3xbd/stdlib.h.html}

Gnulib module: stdlib

Portability problems fixed by Gnulib:
@itemize
@item
The macros @code{EXIT_SUCCESS} and @code{EXIT_FAILURE} are not defined on
some platforms.
@item
The macro @code{EXIT_FAILURE} is incorrectly defined on Tandem/NSK.

@item
Some platforms provide a @code{NULL} macro that cannot be used in arbitrary
expressions:
NetBSD 5.0
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
