@node strings.h
@section @file{strings.h}

POSIX specification: @url{http://www.opengroup.org/susv3xbd/strings.h.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This header file defines symbols, such as @samp{index}, often used for
variables, making debugging harder.
@end itemize
