@node stropts.h
@section @file{stropts.h}

Removed in POSIX.1-2024.
POSIX.1-2017 specification:@* @url{https://pubs.opengroup.org/onlinepubs/9799919799/basedefs/stropts.h.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This header file is missing on some platforms:
macOS 14, FreeBSD 14.0, NetBSD 10.0, OpenBSD 7.5, Minix 3.1.8, Cygwin, mingw, MSVC 14, Android 9.0.
@item
This header is removed in POSIX.1-2024.
@end itemize
