@node sys/uio.h
@section @file{sys/uio.h}

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/sys_uio.h.html}

Gnulib module: sys_uio

Portability problems fixed by Gnulib:
@itemize
@item
This header file is missing on some platforms:
mingw, MSVC 14.
@item
This header file is not self-contained (it requires @code{<sys/types.h>} to be
included first) on some platforms:
OpenBSD 4.4.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
