@node sys/utsname.h
@section @file{sys/utsname.h}

POSIX specification: @url{http://www.opengroup.org/susv3xbd/sys/utsname.h.html}

Gnulib module: sys_utsname

Portability problems fixed by Gnulib:
@itemize
@item
This header file is missing on some platforms:
mingw.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
