@node sys/stat.h
@section @file{sys/stat.h}

POSIX specification: @url{http://www.opengroup.org/susv3xbd/sys/stat.h.html}

Gnulib module: sys_stat

Portability problems fixed by Gnulib:
@itemize
@item
Some macros, such as @code{S_IFMT}, are missing on some platforms.
@item
The macros @code{S_ISBLK}, @code{S_ISCHR}, @code{S_ISDIR}, @code{S_ISFIFO},
@code{S_ISLNK}, @code{S_ISREG}, @code{S_ISSOCK} are broken on some platforms.
@item
Some platforms define macros, such as @code{S_ISDOOR}, that are not defined
on other platforms.
@item
The functions @code{lstat} and @code{mkdir} are not declared on mingw.
@item
The macros @code{UTIME_NOW} and @code{UTIME_OMIT} are missing on some
platforms.
@item
On some platforms, @code{struct stat} does not include @code{st_atim},
@code{st_mtim}, or @code{st_ctim} members.  Use the gnulib module
@samp{stat-time} for accessors to portably get at subsecond resolution.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
