@node sys/time.h
@section @file{sys/time.h}

POSIX specification:@* @url{http://www.opengroup.org/onlinepubs/9699919799/basedefs/sys_time.h.html}

Gnulib module: sys_time

Portability problems fixed by Gnulib:
@itemize
@item
This header file is missing on some platforms:
MSVC 9.
@item
@samp{struct timeval} is not defined on some platforms.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
