@node time.h
@section @file{time.h}

POSIX specification:@* @url{http://www.opengroup.org/onlinepubs/9699919799/basedefs/time.h.html}

Gnulib module: time

Portability problems fixed by Gnulib:
@itemize
@item
@samp{struct timespec} is not defined on some platforms.

@item
Some platforms provide a @code{NULL} macro that cannot be used in arbitrary
expressions:
NetBSD 5.0
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
On some platforms the @code{tv_nsec} member of @code{struct timespec}
is not of type @code{long}, but is of type @code{long long} instead:
glibc x32

@end itemize
