@node time.h
@section @file{time.h}

POSIX specification: @url{http://www.opengroup.org/susv3xbd/time.h.html}

Gnulib module: time

Portability problems fixed by Gnulib:
@itemize
@item
@samp{struct timespec} is not defined on some platforms.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
