@node wctype.h
@section @file{wctype.h}

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9799919799/basedefs/wctype.h.html}

Gnulib module: wctype-h
@mindex wctype-h

Portability problems fixed by Gnulib:
@itemize
@item
This header file is missing on some platforms:
HP-UX 11.00.
@item
The type @code{wint_t} is incorrect on some platforms:
mingw, MSVC 14.
@item
The functions @code{isw*} are missing on some platforms:
FreeBSD 4.11.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
POSIX.1-2024 allows, but does not require, this file to make visible
all symbols from the headers @code{<ctype.h>}, @code{<stdarg.h>},
@code{<stddef.h>}, @code{<stdlib.h>}, @code{<stdio.h>},
@code{<string.h>}, @code{<time.h>}, and @code{<wchar.h>}.
Programs should not assume that these other symbols are visible merely
because this file is included, or that they are invisible because only
this file is included.
@end itemize
