@node wctype.h
@section @file{wctype.h}

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/wctype.h.html}

Gnulib module: wctype-h

Portability problems fixed by Gnulib:
@itemize
@item
This header file is missing on some platforms:
HP-UX 11.00.
@item
The type @code{wint_t} is incorrect on some platforms:
mingw, MSVC 14.
@item
The functions @code{isw*} are missing on some platforms:
FreeBSD 4.11.
@item
The function @code{iswblank} is declared but not defined on some platforms:
IRIX 6.5.30.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
