@node cfgetospeed
@section @code{cfgetospeed}
@findex cfgetospeed

POSIX specification: @url{http://www.opengroup.org/susv3xsh/cfgetospeed.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
mingw.
@end itemize
