@node lseek
@section @code{lseek}
@findex lseek

POSIX specification: @url{http://www.opengroup.org/susv3xsh/lseek.html}

Gnulib module: lseek

Portability problems fixed by Gnulib:
@itemize
@item
This function mistakenly succeeds on pipes on some platforms: mingw.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
POSIX does not specify which file descriptors support seeking and which don't.
In practice, regular files and block devices support seeking, and ttys, pipes,
and most character devices don't support it.
@item
On platforms where @code{off_t} is a 32-bit type, @code{lseek} does not work
correctly with files larger than 2 GB.  The fix is to use the
@code{AC_SYS_LARGEFILE} macro.
@end itemize
