@node memmem
@section @code{memmem}
@findex memmem

Unspecified by POSIX, but comparable to @code{strstr}.

Gnulib module: memmem, memmem-simple

Portability problems fixed by Gnulib:
@itemize
@item
This function has reversed arguments on some older platforms:
Linux libc 5.0.9

@item
This function returns incorrect values in some cases, such as when
given an empty needle (not fixed in memmem-simple):
glibc <= 2.0, cygwin 1.5.x

@item
This function has quadratic instead of linear complexity on some
platforms (not fixed in memmem-simple):
glibc <= 2.6.1, cygwin 1.5.x

@item
This function is missing on some platforms:
Mingw, OpenBSD 4.0
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
