@node socket
@section @code{socket}
@findex socket

POSIX specification: @url{http://www.opengroup.org/susv3xsh/socket.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
mingw.
@item
On BeOS, the descriptors returned by the @code{socket} function can not be used
in calls to @code{read}, @code{write}, and @code{close}; you have to use
@code{recv}, @code{send}, @code{closesocket} in these cases instead.
@end itemize
