@node strcasestr
@section @code{strcasestr}
@findex strcasestr

Unspecified by POSIX, but comparable to a mix of @code{strstr} and
@code{strcasecmp}.

Gnulib module: strcasestr or strcasestr-simple

Portability problems fixed by either Gnulib module @code{strcasestr-simple}
or @code{strcasestr}:
@itemize
@item
This function is missing on some platforms:
MacOS X 10.3, FreeBSD 5.2.1, OpenBSD 4.0, AIX 4.3.2, HP-UX 11, IRIX
6.5, OSF/1 5.1, Solaris 10, Cygwin 1.5.x, mingw, Interix 3.5, BeOS.
@end itemize

Portability problems fixed by Gnulib module @code{strcasestr}:
@itemize
@item
This function has quadratic instead of linear worst-case complexity on some
platforms:
glibc 2.6.1, FreeBSD 6.2, NetBSD 3.0, AIX 5.1.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
