@node String Functions in C Locale
@section Character and String Functions in C Locale

The functions in this section are similar to the generic string functions
from the standard C library, except that
@itemize
@item
They behave as if the locale was set to the "C" locale, even when the
locale is different, and/or
@item
They are specially optimized for the case where all characters are plain
ASCII characters.
@end itemize

@menu
* c-ctype::
* c-strcase::
* c-strcaseeq::
* c-strcasestr::
* c-strstr::
* c-strtod::
* c-strtold::
@end menu

@node c-ctype
@subsection c-ctype
@include c-ctype.texi

@node c-strcase
@subsection c-strcase
@include c-strcase.texi

@node c-strcaseeq
@subsection c-strcaseeq
@include c-strcaseeq.texi

@node c-strcasestr
@subsection c-strcasestr
@include c-strcasestr.texi

@node c-strstr
@subsection c-strstr
@include c-strstr.texi

@node c-strtod
@subsection c-strtod
@include c-strtod.texi

@node c-strtold
@subsection c-strtold
@include c-strtold.texi
