@node error and progname
@section error and progname
@findex error
@findex progname
@vindex program_name

@c Copyright (C) 2007, 2009-2016 Free Software Foundation, Inc.

@c Permission is granted to copy, distribute and/or modify this document
@c under the terms of the GNU Free Documentation License, Version 1.3 or
@c any later version published by the Free Software Foundation; with no
@c Invariant Sections, no Front-Cover Texts, and no Back-Cover
@c Texts.  A copy of the license is included in the ``GNU Free
@c Documentation License'' file as part of this distribution.

The @code{error} function uses the @code{program_name} variable, but
does not depend on the @code{progname} module.  Why?  Because
@code{error} is released under the LGPL, whereas @code{progname} is
GPL.  RMS does not want additional baggage accompanying the
@code{error} module, so an LGPL user must provide their own
replacement @code{program_name}, and a GPL user should manually
specify using the @code{progname} module.

Additionally, using the @code{progname} module is not something that
can be done implicitly. It requires that every @code{main} function
be modified to set @code{program_name} as one of its first actions.
