@node Large File Support
@section Large File Support

This module provides support for files 2 GiB and larger, or with
device or inode numbers exceeding 32 bits.
To this effect, it attempts to ensure that types like @code{off_t} and
@code{ino_t} are 64-bit,
at least on the following platforms:
glibc, Mac OS X, FreeBSD, NetBSD, OpenBSD, AIX, HP-UX, Solaris,
Cygwin, mingw, MSVC.

If the types cannot be made 64-bit, @command{configure} issues a
warning and proceeds.

This module gives
@command{configure} an option @samp{--disable-largefile} that
suppresses support for large files.  This may be useful if the package
links to other libraries whose user-facing ABIs still require
@code{off_t} or most other file-related types to be 32-bit on your
platform.

This module also adds to @command{configure} an option
@code{--enable-year2038}, needed on some platforms to access files
with timestamps past the year 2038.  @xref{Avoiding the year 2038
problem}.
