@node Large File Support
@section Large File Support

The module provides support for files larger than 2 GB, or with device
or inode numbers or timestamps exceeding 32 bits.  To this effect, it
ensures that types like @code{off_t} and @code{time_t} are 64-bit when possible,
at least on the following platforms:
glibc, Mac OS X, FreeBSD, NetBSD, OpenBSD, AIX, HP-UX, IRIX, Solaris,
Cygwin, mingw, MSVC.
