@node sys/timeb.h
@section @file{sys/timeb.h}

Removed in POSIX.1-2008.
POSIX.1-2004 specification:@* @url{https://pubs.opengroup.org/onlinepubs/009695399/basedefs/sys/timeb.h.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This header file is missing on some platforms:
OpenBSD 7.5, Android 9.0.
@end itemize
