@node _longjmp
@section @code{_longjmp}
@findex _longjmp

POSIX specification: @url{http://www.opengroup.org/susv3xsh/_longjmp.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Solaris 2.5.1, mingw.

@item
This function is obsolete; use @code{siglongjmp} instead.
@end itemize
