@node a64l
@section @code{a64l}
@findex a64l

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/a64l.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
FreeBSD 6.0, Minix 3.1.8, mingw, MSVC 14, Android 9.0.
@item
This function was not correctly implemented in glibc versions before 2.2.5.
@end itemize
