@node access
@section @code{access}
@findex access

POSIX specification:@* @url{http://www.opengroup.org/onlinepubs/9699919799/functions/access.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function uses the effective id instead of the real id on some
platforms:
Cygwin 1.5.x.
@end itemize

Other problems of this function:
@itemize
@item
There is an inherent race between calling this function and performing
some action based on the results; you should think twice before trusting
this function, especially in a set-uid or set-gid program.
@item
This function does not have an option for not following symbolic links
(like @code{stat} versus @code{lstat}).  If you need this option, use
the Gnulib module @code{faccessat} with the @code{AT_EACCESS} flag.
@end itemize
