@node acosf
@section @code{acosf}
@findex acosf

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/acosf.html}

Gnulib module: acosf

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Minix 3.1.8, AIX 5.1, Solaris 9.
@item
This function is only defined as a macro with arguments on some platforms:
MSVC 14.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
