@node aio_read
@section @code{aio_read}
@findex aio_read

POSIX specification:@* @url{http://www.opengroup.org/onlinepubs/9699919799/functions/aio_read.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
NetBSD 3.0, OpenBSD 3.8, Minix 3.1.8, OSF/1 5.1, Solaris 2.4, Cygwin, mingw, MSVC 9, Interix 3.5, BeOS.
@item
On platforms where @code{off_t} is a 32-bit type, this function may not
work correctly on files larger than 2 GB.  The fix is to use the
@code{AC_SYS_LARGEFILE} macro.
@end itemize
