@node alphasort
@section @code{alphasort}
@findex alphasort

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/alphasort.html}

Gnulib module: alphasort

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Minix 3.1.8, Solaris 9, mingw, MSVC 14.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
The parameters of this function are declared as @code{const void *} on some platforms:
glibc 2.3.6, macOS 10.7, FreeBSD 6.0, NetBSD 7.1, OpenBSD 6.7.
@item
The parameters of this function are declared as @code{void *} on some platforms:
AIX 5.1.
@end itemize
