@node asctime_r
@section @code{asctime_r}
@findex asctime_r

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/asctime_r.html}

Future POSIX removal:@* @url{https://www.austingroupbugs.net/view.php?id=1410}

Gnulib module: extensions

Portability problems fixed by Gnulib:
@itemize
@item
This function has an incompatible declaration on some platforms:
Solaris 11.4 (when @code{_POSIX_PTHREAD_SEMANTICS} is not defined).
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
mingw, MSVC 14.
@item
POSIX says this function is obsolescent and it is planned to be
removed in a future version.
Use the function @code{strftime} (or even @code{sprintf}) instead.
However, @code{strftime} is locale dependent.
@item
This function may overflow its output buffer if its argument
specifies a year before 1000 or after 9999.
@xref{ctime}.
@end itemize
