@node atexit
@subsection @code{atexit}
@findex atexit

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9799919799/functions/atexit.html}

Gnulib module: atexit
@mindex atexit

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some old platforms.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
The exit status can be incorrect for a process terminated by a signal
during a call to a function registered by @code{atexit}.  This is
because if a signal terminates a process after @code{exit} is called
or @code{main} returns, the process's exit status is that specified by
@code{exit}'s argument or by @code{main}'s return value, instead of
being the exit status corresponding to the signal:
z/OS 3.1.
@end itemize
