@node bsearch
@subsection @code{bsearch}
@findex bsearch

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9799919799/functions/bsearch.html}

Gnulib module: bsearch
@mindex bsearch

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
