@node casinhl
@section @code{casinhl}
@findex casinhl

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/casinhl.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
FreeBSD 11.0, NetBSD 5.0, OpenBSD 3.8, Minix 3.1.8, AIX 5.1, HP-UX 11, IRIX 6.5, Solaris 9, Cygwin 1.7.x, mingw, MSVC 9, Android 7.1.
@end itemize
