@node chmod
@section @code{chmod}
@findex chmod

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/chmod.html}

Gnulib module: chmod

Portability problems fixed by Gnulib:
@itemize
@item
This function does not fail when the file name argument ends in a slash
and (without the slash) names a non-directory, on some platforms:
AIX 7.2, IRIX 6.5.
@item
This function fails with a wrong error code (EINVAL instead of ENOTDIR)
when the file name argument ends in a slash and (without the slash) names
a non-directory, on some platforms:
mingw, MSVC.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
