@node chown
@subsection @code{chown}
@findex chown

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9799919799/functions/chown.html}

Gnulib module: chown
@mindex chown

Portability problems fixed by Gnulib:
@itemize
@item
Some platforms fail to detect trailing slash on non-directories, as in
@code{chown("link-to-file/",uid,gid)}:
macOS 14, FreeBSD 7.2, AIX 7.3.1, Solaris 9.
@item
Some platforms fail to update the change time when at least one
argument was not @minus{}1, but no ownership changes resulted:
OpenBSD 7.7, Cygwin 2.9.0.
@item
When passed an argument of @minus{}1, some implementations really set the owner
user/group id of the file to this value, rather than leaving that id of the
file alone:
some very old platforms.
@item
When applied to a symbolic link, some implementations don't dereference
the symlink, i.e.@: they behave like @code{lchown}:
some very old platforms.
@item
This function is missing on some platforms; however, the replacement
always fails with @code{ENOSYS}:
mingw, MSVC 14.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function sometimes fails with @code{EACCES} when the failure is
due to lack of appropriate privileges (@code{EPERM}), not to
search permission denied on the file name prefix (@code{EACCES}):
Linux kernel 5.15 with glibc 2.35 and a CIFS v1 file system
(see @url{https://bugs.gnu.org/65599}).
@end itemize
