@node clock_getres
@section @code{clock_getres}
@findex clock_getres

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/clock_getres.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Mac OS X 10.11, Minix 3.1.8, mingw, MSVC 14.

@item
On many platforms, this function returns a value other than the clock
resolution of @code{clock_gettime}, i.e., the minimum distance between
differing timestamps.  For example, on AIX 7.2 it returns 10
milliseconds even though the clock resolution is 1 microsecond.
Conversely, on GNU/Linux it typically returns 1 nanosecond even
though the clock resolution may be greater.
@end itemize

The Gnulib module @code{gettime-res} is a partial substitute; it implements
the @code{CLOCK_REALTIME} functionality of @code{clock_getres},
and fixes the too-high resolution bug of platforms like AIX 7.2.
