@node clock_getres
@section @code{clock_getres}
@findex clock_getres

POSIX specification:@* @url{http://www.opengroup.org/onlinepubs/9699919799/functions/clock_getres.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Mac OS X 10.5, Minix 3.1.8, IRIX 5.3, Solaris 2.4, mingw, MSVC 9, Interix 3.5, BeOS.
@end itemize
