@node close
@section @code{close}
@findex close

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/close.html}

Gnulib module: close

Portability problems fixed by Gnulib:
@itemize
@item
This function is declared in a different header file (namely, @code{<io.h>})
on some platforms:
MSVC 14.
@item
This function crashes when invoked with invalid arguments on some platforms:
MSVC 14.
@item
On Windows platforms (excluding Cygwin), @code{socket} and @code{accept}
do not return file descriptors that can be closed by @code{close}.
Instead, @code{closesocket} must be used.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
