@node confstr
@section @code{confstr}
@findex confstr

POSIX specification:@* @url{http://www.opengroup.org/onlinepubs/9699919799/functions/confstr.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Minix 3.1.8, IRIX 5.3, Cygwin 1.5.x, mingw, MSVC 9.
@end itemize
