@node copysignf
@section @code{copysignf}
@findex copysignf

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/copysignf.html}

Gnulib module: copysignf

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Minix 3.1.8, AIX 5.1, older IRIX 6.5, Solaris 9, MSVC 9.
@item
This function is not declared on some platforms:
IRIX 6.5.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
