@node cos
@subsection @code{cos}
@findex cos

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9799919799/functions/cos.html}

Gnulib module: cos
@mindex cos

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
