@node creat
@section @code{creat}
@findex creat

POSIX specification:@* @url{http://www.opengroup.org/onlinepubs/9699919799/functions/creat.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
On Windows, this function returns a file handle in @code{O_TEXT} mode.  If you
need a file handle in @code{O_BINARY} mode, you need to use the function
@code{open} instead.
@item
On platforms where @code{off_t} is a 32-bit type, @code{creat} may not work
correctly to create files larger than 2 GB.  The fix is to use the
@code{AC_SYS_LARGEFILE} macro.
@end itemize
