@node ctime
@section @code{ctime}
@findex ctime

POSIX specification:@* @url{http://www.opengroup.org/onlinepubs/9699919799/functions/ctime.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function may overflow its internal buffer if an invalid year is passed.
@item
The @code{ctime} function need not be reentrant, and consequently is
not required to be thread safe.  Implementations of @code{ctime}
typically write the time stamp into static buffer.  If two threads
call @code{ctime} at roughly the same time, you might end up with the
wrong date in one of the threads, or some undefined string.  There is
a re-entrant interface @code{ctime_r}.
@end itemize

A more flexible function is @code{strftime}.  However, note that it is
locale dependent.
