@node daylight
@section @code{daylight}
@findex daylight

POSIX specification:@* @url{http://www.opengroup.org/onlinepubs/9699919799/functions/daylight.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This variable is missing on some platforms:
Mac OS X 10.3, FreeBSD 6.0, OpenBSD 3.8, IRIX 6.5, OSF/1 5.1.
@item
The address of this variable is not a compile-time constant on some platforms:
Cygwin, mingw.
@end itemize
