@node dbm_clearerr
@section @code{dbm_clearerr}
@findex dbm_clearerr

POSIX specification:@* @url{http://www.opengroup.org/onlinepubs/9699919799/functions/dbm_clearerr.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
glibc 2.3.6, HP-UX 11.11, IRIX 5.3, OSF/1 5.1, Solaris 2.5.1, Cygwin, mingw, MSVC 9, BeOS.
@end itemize
