@node dbm_store
@section @code{dbm_store}
@findex dbm_store

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/dbm_store.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
glibc 2.3.6, Cygwin 2.9, mingw, MSVC 14, Android 9.0.
@end itemize
