@node dcngettext
@subsection @code{dcngettext}
@findex dcngettext

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9799919799/functions/dcngettext.html}

Documentation:
@itemize
@item
@ifinfo
@ref{Advanced gettext functions,,Additional functions for more complicated situations,libc},
@end ifinfo
@ifnotinfo
@url{https://www.gnu.org/software/libc/manual/html_node/Advanced-gettext-functions.html},
@end ifnotinfo
@item
@uref{https://www.kernel.org/doc/man-pages/online/pages/man3/dcngettext.3.html,,man dcngettext}.
@end itemize

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
macOS 14, FreeBSD 14.0, OpenBSD 7.5, Minix 3.1.8, HP-UX 11, Cygwin 2.9, mingw, MSVC 14, Android 9.0.
@item
This function does not treat a @code{LANGUAGE} environment variable
with an empty value like an unset @code{LANGUAGE} environment variable
on some platforms:
NetBSD 10.0.
@end itemize
