@node dlopen
@section @code{dlopen}
@findex dlopen

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/dlopen.html}

LSB specification:@* @url{https://refspecs.linuxbase.org/LSB_5.0.0/LSB-Core-generic/LSB-Core-generic/baselib-dlopen-1.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Minix 3.1.8, mingw, MSVC 14.
@item
If the file name argument is not absolute, the file is searched for.  The
search algorithm is system specific.
@end itemize
