@node encrypt
@subsection @code{encrypt}
@findex encrypt

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9799919799/functions/encrypt.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
NetBSD 5.0, OpenBSD 7.5, Minix 3.1.8, Cygwin 2.9, mingw, MSVC 14, Android 9.0.
@item
This function is not declared in @code{<unistd.h>}
(without @code{-D_GNU_SOURCE}) on some platforms:
glibc (at least 2.11--2.13).
@item
POSIX.1-2024 says this function is obsolescent and it is planned to be
removed in a future version.
@end itemize
