@node erf
@section @code{erf}
@findex erf

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/erf.html}

Gnulib module: erf

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Minix 3.1.8, MSVC 9.
@end itemize
