@node exp
@subsection @code{exp}
@findex exp

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9799919799/functions/exp.html}

Gnulib module: exp or exp-ieee
@mindex exp
@mindex exp-ieee

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
