@node expm1f
@section @code{expm1f}
@findex expm1f

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/expm1f.html}

Gnulib module: expm1f or expm1f-ieee

Portability problems fixed by either Gnulib module @code{expm1f} or @code{expm1f-ieee}:
@itemize
@item
This function is missing on some platforms:
Minix 3.1.8, AIX 5.1, HP-UX 11, Solaris 9, mingw, MSVC 9.
@item
This function produces wrong results for arguments <= @minus{}17.32868 on some platforms:
IRIX 6.5.
@end itemize

Portability problems fixed by Gnulib module @code{expm1f-ieee}:
@itemize
@item
This function returns a positive zero for a minus zero argument
on some platforms:
AIX 7.2.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
