@node fabs
@subsection @code{fabs}
@findex fabs

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9799919799/functions/fabs.html}

Gnulib module: fabs or fabs-ieee
@mindex fabs
@mindex fabs-ieee

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
