@node fchdir
@section @code{fchdir}
@findex fchdir

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/fchdir.html}

Gnulib module: fchdir

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
mingw, MSVC 14.
But the replacement function is not safe to be used in libraries and is not multithread-safe.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
