@node fchdir
@section @code{fchdir}
@findex fchdir

POSIX specification:@* @url{http://www.opengroup.org/onlinepubs/9699919799/functions/fchdir.html}

Gnulib module: fchdir

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Tandem/NSK, mingw, MSVC 9, BeOS.
But the replacement function is not safe to be used in libraries and is not multithread-safe.
@item
This function is not declared on some platforms:
OSF/1 5.1.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
