@node fcntl
@section @code{fcntl}
@findex fcntl

POSIX specification: @url{http://www.opengroup.org/onlinepubs/9699919799/functions/fcntl.html}

Gnulib module: fcntl

Portability problems fixed by Gnulib:
@itemize
@item
This function does not support @code{F_DUPFD_CLOEXEC} on some
platforms:
MacOS X 10.3, FreeBSD 6.0, NetBSD 3.0, OpenBSD 3.8, AIX 5.1, HP-UX 11,
IRIX 6.5, OSF/1 5.1, Solaris 10, Cygwin 1.7.1, mingw, Interix 3.5,
BeOS.
Note that the gnulib replacement code is functional but not atomic.

@item
The @code{F_DUPFD} action of this function does not reject
out-of-range targets properly on some platforms:
Cygwin 1.5.x.

@item
This function is missing on some platforms:
mingw.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
The replacement function does not support @code{F_SETFD},
@code{F_GETFL}, @code{F_SETFL}, @code{F_GETOWN}, @code{F_SETOWN},
@code{F_GETLK}, @code{F_SETLK}, and @code{F_SETLKW} on some platforms:
mingw
@end itemize
