@node fdopendir
@section @code{fdopendir}
@findex fdopendir

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/fdopendir.html}

Gnulib module: fdopendir

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
glibc 2.3.6, Mac OS X 10.5, FreeBSD 6.0, NetBSD 5.0, OpenBSD 3.8, Minix 3.1.8,
AIX 5.1, HP-UX 11, IRIX 6.5, Cygwin 1.5.x, mingw, MSVC 14.
But the replacement function is not safe to be used in libraries and
is not multithread-safe.  Also, the replacement does not guarantee
that @samp{dirfd(fdopendir(n))==n} (dirfd might fail, or return a
different file descriptor than n).
@item
This function exists but is not declared on some platforms:
FreeBSD 7.3.
@item
This function does not reject non-directory file descriptors on some
platforms:
GNU/Hurd.
@item
This function mistakenly closes non-directory file descriptors on some
platforms:
FreeBSD 8.1.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
