@node feclearexcept
@subsection @code{feclearexcept}
@findex feclearexcept

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9799919799/functions/feclearexcept.html}

Gnulib module: fenv-exceptions-tracking-c99
@mindex fenv-exceptions-tracking-c99

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
FreeBSD 6.0, NetBSD 5.0, OpenBSD 3.8, Minix 3.1.8, AIX 5.1, Solaris 9, Cygwin 1.7.7, MSVC 9, Android 4.4.
@item
This function is broken on some platforms:
OpenBSD 7.4/mips64, Minix 3.3/i386.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
