@node fetestexcept
@subsection @code{fetestexcept}
@findex fetestexcept

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9799919799/functions/fetestexcept.html}

Gnulib module: fenv-exceptions-tracking-c99
@mindex fenv-exceptions-tracking-c99

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
FreeBSD 6.0, NetBSD 5.0, OpenBSD 3.8, Minix 3.1.8, AIX 5.1, Solaris 9, Cygwin 1.7.7, MSVC 9, Android 4.4.
@item
This function clears the floating-point exception trap bits on some platforms:
@c It uses an 'fnstenv' instruction without subsequent 'fldenv' or 'fldcw'.
NetBSD 9.3/x86_64.
@item
This function is broken on some platforms:
Minix 3.3/i386.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
