@node fflush
@section @code{fflush}
@findex fflush

POSIX specification: @url{http://www.opengroup.org/susv3xsh/fflush.html}

Gnulib module: fflush

Portability problems fixed by Gnulib:
@itemize
@item
@code{fflush} followed by @code{fseek} or @code{fseeko}, applied to an input
stream, should have the effect of positioning the underlying file descriptor.
It doesn't do this on some platforms.
@item
@code{fflush} on an input stream changes the position of the stream to the
end of the previous buffer, on some platforms: mingw.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
@code{fflush}, @code{ftell}, @code{ftello}, @code{fgetpos} behave incorrectly
on input streams that are opened in @code{O_TEXT} mode and whose contents
contains Unix line terminators (LF), on some platforms: mingw.
@item
On Windows platforms (excluding Cygwin), this function does not set @code{errno}
upon failure.
@end itemize
