@node floor
@section @code{floor}
@findex floor

POSIX specification:@* @url{http://www.opengroup.org/onlinepubs/9699919799/functions/floor.html}

Gnulib module: floor or floor-ieee

Portability problems fixed by either Gnulib module @code{floor} or @code{floor-ieee}:
@itemize
@end itemize

Portability problems fixed by Gnulib module @code{floor-ieee}:
@itemize
@item
This function returns a positive zero for a minus zero argument
on some platforms:
OSF/1 5.1.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
