@node fmtmsg
@section @code{fmtmsg}
@findex fmtmsg

POSIX specification:@* @url{http://www.opengroup.org/onlinepubs/9699919799/functions/fmtmsg.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Mac OS X 10.3, OpenBSD 3.8, Minix 3.1.8, Cygwin, mingw, MSVC 9, Interix 3.5, BeOS.
@end itemize
