@node freeaddrinfo
@section @code{freeaddrinfo}
@findex freeaddrinfo

POSIX specification:@* @url{http://www.opengroup.org/onlinepubs/9699919799/functions/freeaddrinfo.html}

Gnulib module: getaddrinfo

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
HP-UX 11.11, IRIX 6.5, OSF/1 4.0, Solaris 7, Cygwin 1.5.x, mingw, MSVC 9, Interix 3.5, BeOS.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
