@node ftruncate
@section @code{ftruncate}
@findex ftruncate

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/ftruncate.html}

Gnulib module: ftruncate

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
MSVC 14.
@item
On platforms where @code{off_t} is a 32-bit type, this function is not
applicable to arbitrary lengths for files larger than 2 GB@.  The fix is to
use the @code{AC_SYS_LARGEFILE} macro.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
