@node ftw
@section @code{ftw}
@findex ftw

POSIX specification: @url{http://www.opengroup.org/onlinepubs/9699919799/functions/ftw.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
MacOS X 10.3, FreeBSD 5.2.1, NetBSD 3.0, mingw, BeOS.
@end itemize
