@node gai_strerror
@section @code{gai_strerror}
@findex gai_strerror

POSIX specification:@* @url{http://www.opengroup.org/onlinepubs/9699919799/functions/gai_strerror.html}

Gnulib module: getaddrinfo

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
HP-UX 11.11, IRIX 6.5, OSF/1 4.0, Solaris 7, Cygwin 1.5.x, Interix
3.5, BeOS.
@item
This function is only available in @code{<ws2tcpip.h>} on some
platforms:
mingw, MSVC 9.
@item
This function's return type is @code{char *} instead of @code{const char *}
on some platforms:
AIX 7.1, HP-UX 11, OSF/1 5.1, Solaris 9, mingw, MSVC 9.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
