@node getdate_err
@section @code{getdate_err}
@findex getdate_err

POSIX specification:@* @url{http://www.opengroup.org/onlinepubs/9699919799/functions/getdate_err.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This variable is missing on some platforms:
Mac OS X 10.5, FreeBSD 6.0, NetBSD 5.0, OpenBSD 3.8, Minix 3.1.8, IRIX 6.5, OSF/1 5.1, Cygwin, mingw, MSVC 9, BeOS.
@end itemize
