@node getnameinfo
@section @code{getnameinfo}
@findex getnameinfo

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/getnameinfo.html}

Gnulib module: getaddrinfo

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
HP-UX 11.11, IRIX 6.5, Cygwin 1.5.x, mingw, MSVC 14.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
