@node getprotobyname
@subsection @code{getprotobyname}
@findex getprotobyname

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9799919799/functions/getprotobyname.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is declared in @code{<winsock2.h>} instead of @code{<netdb.h>}
on some platforms:
mingw, MSVC 14.
@end itemize
