@node getpeername
@section @code{getpeername}
@findex getpeername

POSIX specification:@* @url{http://www.opengroup.org/onlinepubs/9699919799/functions/getpeername.html}

Gnulib module: getpeername

Portability problems fixed by Gnulib:
@itemize
@item
On Windows platforms (excluding Cygwin), error codes for
@code{getpeername} are not placed in @code{errno}, and
@code{WSAGetLastError} must be used instead.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
Some platforms don't have a @code{socklen_t} type; in this case this function's
third argument type is @samp{int *}.
@end itemize
