@node getpwnam_r
@section @code{getpwnam_r}
@findex getpwnam_r

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/getpwnam_r.html}

Gnulib module: extensions

Portability problems fixed by Gnulib:
@itemize
@item
This function has an incompatible declaration on some platforms:
Solaris 11.3 (when @code{_POSIX_PTHREAD_SEMANTICS} is not defined).
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
OpenBSD 3.8, Minix 3.1.8, mingw, MSVC 14, Android 3.0.
@end itemize
