@node getpid
@subsection @code{getpid}
@findex getpid

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9799919799/functions/getpid.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
