@node getpwnam_r
@section @code{getpwnam_r}
@findex getpwnam_r

POSIX specification:@* @url{http://www.opengroup.org/onlinepubs/9699919799/functions/getpwnam_r.html}

Gnulib module: extensions

Portability problems fixed by Gnulib:
@itemize
@item
This function has an incompatible declaration on some platforms:
Solaris 11 2011-11 (when @code{_POSIX_PTHREAD_SEMANTICS} is not defined).
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
OpenBSD 3.8, Minix 3.1.8, mingw, MSVC 9, BeOS.
@item
This function has an incompatible declaration, with fewer than five
arguments, on some platforms:
IRIX 5.3.
@end itemize
