@node getsockopt
@section @code{getsockopt}
@findex getsockopt

POSIX specification:@* @url{http://www.opengroup.org/onlinepubs/9699919799/functions/getsockopt.html}

Gnulib module: getsockopt

Portability problems fixed by Gnulib:
@itemize
@item
On Windows platforms (excluding Cygwin), error codes for
@code{getsockopt} are not placed in @code{errno}, and
@code{WSAGetLastError} must be used instead.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
BeOS.
@item
Some platforms don't have a @code{socklen_t} type; in this case this function's
fifth argument type is @samp{int *}.
@item
Many socket options are not available on all platforms.
@item
BeOS has the @code{setsockopt} function, but not the @code{getsockopt}
function.
@end itemize
