@node getservbyname
@subsection @code{getservbyname}
@findex getservbyname

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9799919799/functions/getservbyname.html}

Gnulib module: servent

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
@end itemize
