@node globfree
@section @code{globfree}
@findex globfree

POSIX specification: @url{http://www.opengroup.org/susv3xsh/globfree.html}

Gnulib module: glob

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
IRIX 5.3, mingw, BeOS.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
