@node glob
@subsection @code{glob}
@findex glob

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9799919799/functions/glob.html}

Gnulib module: glob
@mindex glob

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
mingw, MSVC 14, Android 8.1.
@item
This function does not list symbolic links to nonexistent files among the results,
on some platforms:
glibc 2.26, AIX 7.2, HP-UX 11, Solaris 11.4.
@item
On platforms where @code{off_t} is a 32-bit type, this function may not
work correctly on huge directories 2 GiB and larger.
@xref{Large File Support}.
@item
This function makes a recursive call for every trailing @code{/} and
every @code{/} following a wildcard character on some platforms, which
can cause the stack to overflow:
@c https://sourceware.org/PR30635
@c https://sourceware.org/PR33537
glibc 2.42,
Cygwin, Android.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
Some platforms may store additional flags in the @code{gl_flags} field.
@end itemize
