@node gmtime
@section @code{gmtime}
@findex gmtime

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/gmtime.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
On some platforms, this function yields incorrect values for
timestamps before the year 1:
MacOS X 10.5, Solaris 11.3.
@end itemize
