@node htonl
@section @code{htonl}
@findex htonl

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/htonl.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
HP-UX 11, mingw, MSVC 14, Android 4.4.
@end itemize
