@node iconv_close
@subsection @code{iconv_close}
@findex iconv_close

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9799919799/functions/iconv_close.html}

Gnulib module: iconv
@mindex iconv

Portability problems fixed by Gnulib:
@itemize
@item
GNU libiconv is not found if installed in @file{$PREFIX/lib}.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
FreeBSD 6.0, OpenBSD 7.5, Minix 3.1.8, Cygwin 2.9, mingw, MSVC 14, Android 8.1,
when GNU libiconv is not installed.
@end itemize
