@node iconv_close
@section @code{iconv_close}
@findex iconv_close

POSIX specification:@* @url{http://www.opengroup.org/onlinepubs/9699919799/functions/iconv_close.html}

Gnulib module: iconv

Portability problems fixed by Gnulib:
@itemize
@item
GNU libiconv is not found if installed in @file{$PREFIX/lib}.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Mac OS X 10.5, FreeBSD 6.0, OpenBSD 3.8, Minix 3.1.8, IRIX 5.3, Cygwin, mingw, MSVC 9, BeOS,
when GNU libiconv is not installed.
@end itemize
