@node if_freenameindex
@section @code{if_freenameindex}
@findex if_freenameindex

POSIX specification:@* @url{http://www.opengroup.org/onlinepubs/9699919799/functions/if_freenameindex.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
OpenBSD 3.8, Minix 3.1.8, HP-UX 11.23, IRIX 6.5, OSF/1 4.0, Solaris 7, Cygwin 1.5.x,
mingw, MSVC 9, Interix 3.5, BeOS.

@item
This is available only as a macro, rather than a function, on some
platforms:
OpenBSD 4.6, MirBSD 10.
@end itemize
