@node initstate
@section @code{initstate}
@findex initstate

POSIX specification:@* @url{http://www.opengroup.org/onlinepubs/9699919799/functions/initstate.html}

Gnulib module: random

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Solaris 2.4, mingw, MSVC 9.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
