@node ioctl
@section @code{ioctl}
@findex ioctl

POSIX specification: @url{http://www.opengroup.org/susv3xsh/ioctl.html}

Gnulib module: ioctl

Portability problems fixed by Gnulib:
@itemize
@item
On Windows platforms (excluding Cygwin), error codes for @code{ioctl}
are not placed in @code{errno}, and @code{WSAGetLastError} must be
used instead.
@item
@code{ioctl} is called @code{ioctlsocket} under mingw
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
Most @code{ioctl} requests are platform and hardware specific.
@end itemize
