@node isatty
@section @code{isatty}
@findex isatty

POSIX specification: @url{http://www.opengroup.org/onlinepubs/9699919799/functions/isatty.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
On Windows, @code{isatty} also returns true for character devices such as
@file{NUL}.
@end itemize
