@node isdigit
@subsection @code{isdigit}
@findex isdigit

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9799919799/functions/isdigit.html}

Gnulib module: ctype
@mindex ctype

Portability problems fixed by Gnulib:
@itemize
@item
This function cannot be called from plain inline or extern inline functions
on some platforms:
macOS 10.8.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function's behavior depends on locale, and it can return nonzero on
arguments other than the usual decimal digits:
mingw, MSVC.
@end itemize

Note: This function does not support
the multibyte characters that occur in strings in locales with
@code{MB_CUR_MAX > 1} (this includes all the common UTF-8 locales).
There are five alternative APIs:

@table @code
@item c_isdigit
@mindex c-ctype
This function operates in a locale independent way and returns true only for
ASCII characters.  It is provided by the Gnulib module @samp{c-ctype}.

@item iswdigit
@mindex wctype
This function operates in a locale dependent way, on wide characters.  In
order to use it, you first have to convert from multibyte to wide characters,
using the @code{mbrtowc} function.  It is provided by the Gnulib module
@samp{wctype}.

@item c32isdigit
@mindex c32isdigit
This function operates in a locale dependent way, on 32-bit wide characters.
In order to use it, you first have to convert from multibyte to 32-bit wide
characters, using the @code{mbrtoc32} function.  It is provided by the
Gnulib module @samp{c32isdigit}.

@item mb_isdigit
@mindex mbchar
This function operates in a locale dependent way, on multibyte characters.
It is provided by the Gnulib module @samp{mbchar}.

@item uc_is_digit
@mindex unictype/ctype-digit
This function operates in a locale independent way, on Unicode characters.
It is provided by the Gnulib module @samp{unictype/ctype-digit}.
@end table
