@node isfinite
@section @code{isfinite}
@findex isfinite

POSIX specification:@* @url{http://www.opengroup.org/onlinepubs/9699919799/functions/isfinite.html}

Gnulib module: isfinite

Portability problems fixed by Gnulib:
@itemize
@item
This macro is missing on some platforms:
MacOS X 10.5, OpenBSD 3.8, AIX 5.1, IRIX 6.5, OSF/1 5.1, Solaris 11 2011-11, Interix 3.5.
@item
This macro incorrectly yields true for some @samp{double} arguments, on some
platforms:
Linux/ia64 (signalling NaNs).
@item
This macro incorrectly yields true for some @samp{long double} arguments, on
some platforms:
x86 (pseudo-zeroes, unnormalized numbers, pseudo-denormals),
x86_64 (pseudo-denormals),
ia64 (pseudo-NaN, pseudo-Infinity, pseudo-zeroes, unnormalized numbers, pseudo-denormals).
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
It is implementation-dependent whether @code{isfinite} raises an
exception given a signaling NaN operand.
@end itemize
