@node isfinite
@section @code{isfinite}
@findex isfinite

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/isfinite.html}

Gnulib module: isfinite

Portability problems fixed by Gnulib:
@itemize
@item
This macro is missing on some platforms:
macOS 11.1, OpenBSD 6.7, AIX 5.1, IRIX 6.5, Solaris 11.4.
@item
This macro incorrectly yields true for some @samp{double} arguments, on some
platforms:
Linux/ia64 (signalling NaNs).
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
It is implementation-dependent whether @code{isfinite} raises an
exception given a signaling NaN operand.
@item
This macro returns an unspecified result when given noncanonical values
such as unnormalized numbers, pseudo-denormals, pseudo-NaNs,
pseudo-Infinities, and pseudo-zeroes.
@end itemize
