@node isgraph_l
@subsection @code{isgraph_l}
@findex isgraph_l

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9799919799/functions/isgraph_l.html}

Gnulib module: isgraph_l
@mindex isgraph_l

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on many platforms:
FreeBSD 9.0, NetBSD 6.1, OpenBSD 6.1, Minix 3.1.8, AIX 6.1, HP-UX 11, Solaris 11.3, Cygwin 2.5.x, mingw, MSVC 14, Android 4.4.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
