@node isinf
@section @code{isinf}
@findex isinf

POSIX specification: @url{http://www.opengroup.org/onlinepubs/9699919799/functions/isinf.html}

Gnulib module: isinf

Portability problems fixed by Gnulib:
@itemize
@item
This macro is missing on some platforms:
AIX 4.3.2, IRIX 6.5, OSF/1 5.1, Solaris 10.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
