@node iswpunct
@section @code{iswpunct}
@findex iswpunct

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/iswpunct.html}

Gnulib module: wctype-h

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Minix 3.1.8.
@item
This function cannot be called from plain inline or extern inline functions
on some platforms:
OS X 10.8.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
On Windows and 32-bit AIX platforms, @code{wchar_t} is a 16-bit type and
therefore cannot accommodate all Unicode characters.
However, the Gnulib function @code{c32ispunct}, provided by Gnulib module
@code{c32ispunct}, operates on 32-bit wide characters and therefore does not
have this limitation.
@end itemize
