@node isxdigit_l
@section @code{isxdigit_l}
@findex isxdigit_l

POSIX specification:@* @url{http://www.opengroup.org/onlinepubs/9699919799/functions/isxdigit_l.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on many platforms:
Mac OS X 10.3, FreeBSD 6.0, NetBSD 5.0, OpenBSD 3.8, Minix 3.1.8, AIX 5.1, HP-UX 11, IRIX 6.5, OSF/1 5.1, Solaris 11 2011-11, Cygwin, mingw, MSVC 9, Interix 3.5, BeOS.
@end itemize
