@node j1
@section @code{j1}
@findex j1

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/j1.html}

Gnulib module: j1

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Minix 3.1.8.
@end itemize
