@node ldexpl
@section @code{ldexpl}
@findex ldexpl

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/ldexpl.html}

Gnulib module: ldexpl

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
FreeBSD 5.2.1, NetBSD 5.0, OpenBSD 3.8, Minix 3.1.8, HP-UX 11, IRIX 6.5, Solaris 9, Cygwin 1.7.x.
@item
This function is only defined as a macro with arguments on some platforms:
MSVC 14.
@item
This function has no prototype in @code{<math.h>} on some platforms:
Mac OS X.
@item
This function does not work on finite numbers on some platforms:
AIX 5.1.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
