@node ldexp
@subsection @code{ldexp}
@findex ldexp

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9799919799/functions/ldexp.html}

Gnulib module: ldexp or ldexp-ieee
@mindex ldexp
@mindex ldexp-ieee

Portability problems fixed by Gnulib:
@itemize
@item
This function produces wrong results on some platforms:
@c ldexp(1.9269695883136991774e-308,0) returns 7.32274e-245.
OpenBSD 7.3/mips64.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
