@node lgamma
@section @code{lgamma}
@findex lgamma

POSIX specification:@* @url{http://www.opengroup.org/onlinepubs/9699919799/functions/lgamma.html}

Gnulib module: lgamma

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Minix 3.1.8, MSVC 9.
@item
This function is not declared on some platforms:
IRIX 5.3.
@end itemize
