@node link
@subsection @code{link}
@findex link

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9799919799/functions/link.html}

LSB specification:@* @url{https://refspecs.linuxbase.org/LSB_5.0.0/LSB-Core-generic/LSB-Core-generic/baselib-link-1.html}

Gnulib module: link
@mindex link

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
mingw, MSVC 14.
@item
This function fails to reject trailing slashes on non-directories on
some platforms:
FreeBSD 7.2, Solaris 11.3, Cygwin 1.5.x.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
When the first argument is a symlink, some platforms create a
hard-link to what the symlink referenced, rather than to the symlink
itself.  Use @samp{linkat} to force a particular behavior.
@end itemize
