@node link
@section @code{link}
@findex link

POSIX specification: @url{http://www.opengroup.org/onlinepubs/9699919799/functions/link.html}

Gnulib module: link

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
mingw.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
