@node llrint
@section @code{llrint}
@findex llrint

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/llrint.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
FreeBSD 5.2.1, OpenBSD 3.8, Minix 3.1.8, AIX 5.1, IRIX 6.5, Solaris 9,
Cygwin 1.5.x, MSVC 9.
@end itemize
