@node localtime
@section @code{localtime}
@findex localtime

POSIX specification:@* @url{http://www.opengroup.org/onlinepubs/9699919799/functions/localtime.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item On some platforms, this function returns nonsense values for
unsupported arguments (like @math{2^56}), rather than failing:
FreeBSD 10.
@end itemize
