@node localtime_r
@section @code{localtime_r}
@findex localtime_r

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/localtime_r.html}

Gnulib module: time_r

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
mingw, MSVC 14.
@item
This function is not declared unless @code{_REENTRANT} is defined,
on some platforms:
HP-UX 11.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
On some platforms, this function loops forever for values
near extrema (such as the year @math{-2**31}):
Mac OS X 10.6.
You can use the @code{time_rz} module to work around the problem.
@item
On some platforms, this function returns nonsense values for
unsupported arguments (like @math{2^56}), rather than failing:
FreeBSD 10.
@item
On some platforms, this function yields incorrect values for
timestamps before the year 1:
MacOS X 10.5, Solaris 11.3.
@end itemize
