@node localeconv
@section @code{localeconv}
@findex localeconv

POSIX specification: @url{http://www.opengroup.org/onlinepubs/9699919799/functions/localeconv.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
