@node log
@section @code{log}
@findex log

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/log.html}

Gnulib module: log or log-ieee

Portability problems fixed by either Gnulib module @code{log} or @code{log-ieee}:
@itemize
@end itemize

Portability problems fixed by Gnulib module @code{log-ieee}:
@itemize
@item
This function returns a wrong value for a negative argument on some platforms:
NetBSD 5.1, Solaris 11.4.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
