@node log10
@section @code{log10}
@findex log10

POSIX specification:@* @url{http://www.opengroup.org/onlinepubs/9699919799/functions/log10.html}

Gnulib module: log10

Portability problems fixed by Gnulib:
@itemize
@item
This function returns a wrong value for a minus zero argument on some platforms:
OSF/1 5.1.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
