@node log2l
@section @code{log2l}
@findex log2l

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/log2l.html}

Gnulib module: log2l

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
FreeBSD 6.0, NetBSD 9.0, OpenBSD 3.8, Minix 3.1.8, AIX 5.1, HP-UX 11, older IRIX 6.5, Solaris 9, Cygwin 1.7.x, MSVC 9, Android 4.2.
@item
This function is not declared on some platforms:
IRIX 6.5.
@item
This function produces results which are accurate to only 16 digits on some
platforms:
musl libc 1.2.2/arm64, musl libc 1.2.2/s390x.
@item
This function returns Infinity for some large finite arguments on some platforms:
musl libc 1.2.2/arm64, musl libc 1.2.2/s390x.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
