@node log2
@section @code{log2}
@findex log2

POSIX specification:@* @url{http://www.opengroup.org/onlinepubs/9699919799/functions/log2.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
MacOS X 10.5, FreeBSD 6.0, NetBSD 3.0, OpenBSD 3.8, Minix 3.1.8, AIX 5.1, IRIX 6.5,
Solaris 9, Interix 3.5.
@item
This function is only provided as a macro on some platforms:
Cygwin 1.5.x.
@end itemize
