@node logl
@section @code{logl}
@findex logl

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/logl.html}

Gnulib module: logl

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
FreeBSD 6.0, NetBSD 5.0, OpenBSD 3.8, Minix 3.1.8, HP-UX 11, IRIX 6.5, Solaris 9, Cygwin 1.7.x, Android 4.4.
@item
This function is only defined as a macro with arguments on some platforms:
MSVC 14.
@item
This function returns wrong results on some platforms:
glibc 2.7 on Linux/SPARC64.
@item
This function produces results which are accurate to only 16 digits on some
platforms:
musl libc 1.2.2/arm64, musl libc 1.2.2/s390x, NetBSD 9.0.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
