@node lstat
@section @code{lstat}
@findex lstat

POSIX specification: @url{http://www.opengroup.org/onlinepubs/9699919799/functions/lstat.html}

Gnulib module: lstat

Portability problems fixed by Gnulib:
@itemize
@item
When the argument ends in a slash, some platforms don't dereference the
argument.
@item
On Windows platforms (excluding Cygwin), symlinks are not supported, so
@code{lstat} does not exist.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
On platforms where @code{off_t} is a 32-bit type, @code{lstat} may not
correctly report the size of files or block devices larger than 2 GB.  The fix
is to use the @code{AC_SYS_LARGEFILE} macro.
@end itemize
