@node mblen
@subsection @code{mblen}
@findex mblen

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9799919799/functions/mblen.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Android 7.1.
@item
On some platforms, when using a multibyte encoding other than UTF-8,
this function may incorrectly return the length of an invalid byte sequence
instead of returning @code{(size_t) -1}:
FreeBSD 15, NetBSD 11, DragonFly BSD 6, OS X 10.9.
@end itemize
