@node mbrtoc8
@section @code{mbrtoc8}
@findex mbrtoc8

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on most platforms:
glibc 2.29, macOS 11.1, FreeBSD 14.0, NetBSD 10.0, OpenBSD 6.7, Minix 3.3.0, AIX 7.1, HP-UX 11.31, Solaris 11.4, Cygwin 3.4.6, mingw, MSVC 14, Android 9.0.
@end itemize
