@node mbrtoc8
@subsection @code{mbrtoc8}
@findex mbrtoc8

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on most platforms:
glibc 2.35, macOS 14, FreeBSD 14.0, NetBSD 10.0, OpenBSD 7.5, Minix 3.3.0, AIX 7.1, HP-UX 11.31, Solaris 11.4,
@c https://cygwin.com/pipermail/cygwin/2024-August/256326.html
Cygwin,
mingw, MSVC 14, Android 9.0.
@end itemize
