@node memchr
@section @code{memchr}
@findex memchr

POSIX specification:@* @url{http://www.opengroup.org/onlinepubs/9699919799/functions/memchr.html}

Gnulib module: memchr or memchr-obsolete

Portability problems fixed by either Gnulib module @code{memchr} or @code{memchr-obsolete}:
@itemize
@item
This function dereferences too much memory on some platforms:
glibc 2.10 on x86_64, IA-64; glibc 2.11 on Alpha.
@end itemize

Portability problems fixed by Gnulib module @code{memchr-obsolete}:
@itemize
@item
This function is missing on some older platforms.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
