@node memccpy
@section @code{memccpy}
@findex memccpy

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/memccpy.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
