@node mkdirat
@section @code{mkdirat}
@findex mkdirat

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/mkdirat.html}

Gnulib module: mkdirat

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
glibc 2.3.6, Mac OS X 10.5, FreeBSD 6.0, NetBSD 5.0, OpenBSD 3.8, Minix 3.1.8,
AIX 5.1, HP-UX 11, IRIX 6.5, Solaris 10, Cygwin 1.5.x, mingw, MSVC 14.
But the replacement function is not safe to be used in libraries and is not multithread-safe.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
