@node mknod
@section @code{mknod}
@findex mknod

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/mknod.html}

Gnulib module: mknod

Portability problems fixed by Gnulib:
@itemize
@item
This function requires super-user privileges to create a fifo:
FreeBSD 7.2, NetBSD 8.0, OpenBSD 6.7.
@item
This function mishandles trailing slash on some platforms:
FreeBSD 7.2, Solaris 9.
@item
This function is missing on some platforms; however, the replacement
always fails with @code{ENOSYS}:
mingw, MSVC 14.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
Use of this function for anything except fifos is not portable,
generally requiring super-user privileges and knowledge of supported
device numbers.
@item
If the argument exists and is a directory, this function fails with
@code{EISDIR} instead of the correct @code{EEXIST}:
HP-UX 11.11.
@end itemize
