@node mq_timedsend
@section @code{mq_timedsend}
@findex mq_timedsend

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/mq_timedsend.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
macOS 11.1, FreeBSD 6.0, NetBSD 3.0, OpenBSD 6.7, Minix 3.1.8, AIX 5.1, HP-UX 11, IRIX 6.5, Solaris 9, Cygwin 1.5.x, mingw, MSVC 14, Android 9.0.
@end itemize
