@node msgrcv
@section @code{msgrcv}
@findex msgrcv

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/msgrcv.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Minix 3.1.8, mingw, MSVC 14, Android 7.1.
@end itemize
