@node msync
@section @code{msync}
@findex msync

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/msync.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Minix 3.1.8, mingw, MSVC 14.
@item
On NetBSD, @code{msync} takes only two arguments.
@end itemize
