@node msync
@subsection @code{msync}
@findex msync

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9799919799/functions/msync.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Minix 3.1.8, mingw, MSVC 14.
@item
On NetBSD, @code{msync} takes only two arguments.
@item
On Solaris 10 this function accepts @code{char *} not @code{void *},
unless you define feature test macros like @code{_POSIX_C_SOURCE}
or @code{_XOPEN_SOURCE} that may undesirably hide other symbols.
To work around this problem, callers can limit themselves to either
@code{void *} or @code{char *}.
@end itemize
