@node opendir
@subsection @code{opendir}
@findex opendir

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9799919799/functions/opendir.html}

Gnulib module: opendir
@mindex opendir

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
MSVC 14.
@item
On platforms where @code{off_t} is a 32-bit type, this function may not
work correctly on huge directories 2 GiB and larger.  Also, on platforms
where @code{ino_t} is a 32-bit type, this function may report inode numbers
incorrectly.  @xref{Large File Support}.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
