@node open
@section @code{open}
@findex open

POSIX specification:@* @url{http://www.opengroup.org/onlinepubs/9699919799/functions/open.html}

Gnulib module: open, fchdir

Portability problems fixed by the Gnulib module open:
@itemize
@item
This function does not fail when the file name argument ends in a slash
and (without the slash) names a nonexistent file or a file that is not a
directory, on some platforms:
FreeBSD 7.2, AIX 7.1, HP-UX 11.00, Solaris 9, Irix 5.3.
@item
This function does not support the @code{O_NONBLOCK} flag when it is defined
by the gnulib module @code{nonblock} on some platforms:
mingw.
@item
On Windows platforms (excluding Cygwin), this function does usually not
recognize the @file{/dev/null} filename.
@end itemize

Portability problems fixed by the Gnulib module fchdir:
@itemize
@item
On Windows platforms (excluding Cygwin), this function fails to open a
read-only descriptor for directories.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
On Windows, this function returns a file handle in @code{O_TEXT} mode by
default; this means that it translates '\n' to CR/LF by default.  Use the
@code{O_BINARY} flag if you need reliable binary I/O.
@item
On platforms where @code{off_t} is a 32-bit type, @code{open} may not work
correctly with files larger than 2 GB.  The fix is to use the
@code{AC_SYS_LARGEFILE} macro.
@end itemize
