@node openat
@section @code{openat}
@findex openat

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/openat.html}

Gnulib module: openat

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
glibc 2.3.6, Mac OS X 10.5, FreeBSD 6.0, NetBSD 5.0, OpenBSD 3.8, Minix 3.1.8,
AIX 5.1, HP-UX 11, IRIX 6.5, Cygwin 1.5.x, mingw, MSVC 14.
But the replacement function is not safe to be used in libraries and is not multithread-safe.
@item
Some platforms do not support @code{O_CLOEXEC}:
AIX 7.1, Solaris 10.
@item
On platforms where @code{off_t} is a 32-bit type, @code{open} may not work
correctly with files larger than 2 GB@.  (Cf. @code{AC_SYS_LARGEFILE}.)
@item
This function does not fail when the file name argument ends in a slash
and (without the slash) names a nonexistent file or a file that is not a
directory, on some platforms:
Solaris 9.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
The Gnulib replacement for @code{O_CLOEXEC} is not atomic, and so is
not safe in the presence of multiple threads or signal handlers.
@item
@code{openat (fd, "symlink", O_NOFOLLOW ...)} fails with @code{errno}
set to @code{EMLINK} instead of the POSIX-required @code{ELOOP} on
some platforms:
FreeBSD 10.1.
@item
@code{openat (fd, "symlink", O_NOFOLLOW ...)} fails with @code{errno}
set to @code{EFTYPE} instead of the POSIX-required @code{ELOOP} on
some platforms:
NetBSD 6.1.
@end itemize
