@node optarg
@section @code{optarg}
@findex optarg

POSIX specification:@* @url{http://www.opengroup.org/onlinepubs/9699919799/functions/optarg.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This variable is missing on some platforms:
Mac OS X 10.5, IRIX 6.5, OSF/1 5.1, MSVC 9.
@end itemize
