@node optind
@section @code{optind}
@findex optind

POSIX specification:@* @url{http://www.opengroup.org/onlinepubs/9699919799/functions/optind.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This variable is missing on some platforms:
IRIX 6.5, OSF/1 5.1, MSVC 9.
@end itemize
