@node optopt
@section @code{optopt}
@findex optopt

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/optopt.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This variable is missing on some platforms:
Mac OS X 10.5, IRIX 6.5, MSVC 14.
@end itemize
