@node pclose
@section @code{pclose}
@findex pclose

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/pclose.html}

Gnulib module: pclose

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
MSVC 14.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
