@node perror
@section @code{perror}
@findex perror

POSIX specification:@* @url{http://www.opengroup.org/onlinepubs/9699919799/functions/perror.html}

Gnulib module: perror

Portability problems fixed by Gnulib:
@itemize
@item
This function does not support the error values that are specified by POSIX
but not defined by the system, on some platforms:
OpenBSD 4.0, OSF/1 5.1, Cygwin 1.5.x, mingw.
@item
This function treats @code{errno} of 0 like failure, although POSIX
requires that the message declare it as a success, on some platforms:
FreeBSD 8.2
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
POSIX requires that this function set the stream error bit (detected
by @code{ferror}) on write failure, but not all platforms do this:
glibc 2.13.
@end itemize
