@node poll
@section @code{poll}
@findex poll

POSIX specification:@* @url{http://www.opengroup.org/onlinepubs/9699919799/functions/poll.html}

Gnulib module: poll

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
mingw, MSVC 9, BeOS.
@item
This function doesn't work on special files like @file{/dev/null} and ttys like
@file{/dev/tty} on some platforms:
MacOS X 10.4.0, AIX 5.3.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
