@node posix_spawnattr_setsigmask
@section @code{posix_spawnattr_setsigmask}
@findex posix_spawnattr_setsigmask

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/posix_spawnattr_setsigmask.html}

Gnulib module: posix_spawnattr_setsigmask

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
FreeBSD 6.0, NetBSD 5.0, OpenBSD 3.8, Minix 3.1.8, AIX 5.1, HP-UX 11, IRIX 6.5, Solaris 9, Cygwin 1.7.x, mingw, MSVC 14, Android 8.1.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
