@node pselect
@section @code{pselect}
@findex pselect

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/pselect.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
OpenBSD 3.8, Minix 3.1.8, AIX 5.1, HP-UX 11.23, IRIX 6.5, Solaris 9, mingw, MSVC 14.
@item
On some platforms, this function fails to detect invalid fds with
EBADF, but only if they lie beyond the current maximum open fd:
FreeBSD 8.2.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function has a slightly incompatible declaration on some platforms:
AIX 7.1 (when @code{_ALL_SOURCE} is defined).
@item
When the @var{sigmask} argument is nonnull on platforms that do not
natively support this function, race conditions are possible when its
gnulib implementation temporarily modifies the signal mask, and the
behavior is unspecified in a multi-threaded process.
@end itemize
