@node pthread_spin_destroy
@section @code{pthread_spin_destroy}
@findex pthread_spin_destroy

POSIX specification:@* @url{http://www.opengroup.org/onlinepubs/9699919799/functions/pthread_spin_destroy.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Mac OS X 10.5, FreeBSD 5.2.1, OpenBSD 3.8, Minix 3.1.8, AIX 5.1, HP-UX 11, IRIX 6.5, OSF/1 5.1, Solaris 9, Cygwin 1.7.9, mingw, MSVC 9, BeOS.
@end itemize
