@node pthread_spin_unlock
@section @code{pthread_spin_unlock}
@findex pthread_spin_unlock

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_spin_unlock.html}

Gnulib module: pthread-spin

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
macOS 11.1, FreeBSD 5.2.1, OpenBSD 3.8, Minix 3.1.8, AIX 5.1, HP-UX 11, IRIX 6.5, Solaris 9, Cygwin 1.7.9, mingw, MSVC 14, Android 6.0.
But the provided replacement is just a dummy on some of these platforms:
Minix 3.1.8.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
