@node pthread_cleanup_pop
@section @code{pthread_cleanup_pop}
@findex pthread_cleanup_pop

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_cleanup_pop.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
glibc 2.3.6, macOS 11.1, NetBSD 9.0, Minix 3.1.8, HP-UX 11, IRIX 6.5, Solaris 11.4, Cygwin 2.9, mingw, MSVC 14, Android 9.0.
@end itemize
