@node pthread_attr_setinheritsched
@section @code{pthread_attr_setinheritsched}
@findex pthread_attr_setinheritsched

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_attr_setinheritsched.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Minix 3.1.8, mingw, MSVC 14, Android 9.0.
@end itemize
