@node pthread_cond_signal
@section @code{pthread_cond_signal}
@findex pthread_cond_signal

POSIX specification:@* @url{http://www.opengroup.org/onlinepubs/9699919799/functions/pthread_cond_signal.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Minix 3.1.8, IRIX 5.3, Solaris 2.4, mingw, MSVC 9, BeOS.
@end itemize
