@node pthread_rwlockattr_getpshared
@section @code{pthread_rwlockattr_getpshared}
@findex pthread_rwlockattr_getpshared

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_rwlockattr_getpshared.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
NetBSD 9.0, Minix 3.1.8, mingw, MSVC 14.
@end itemize
