@node pthread_rwlock_clockrdlock
@subsection @code{pthread_rwlock_clockrdlock}
@findex pthread_rwlock_clockrdlock

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9799919799/functions/pthread_rwlock_clockrdlock.html}

Documentation:
@itemize
@item
@ifinfo
@ref{Non-POSIX Extensions,,Non-POSIX Extensions,libc},
@end ifinfo
@ifnotinfo
@url{https://www.gnu.org/software/libc/manual/html_node/Non_002dPOSIX-Extensions.html},
@end ifnotinfo
@end itemize

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on many platforms:
macOS 14, FreeBSD 14.0, NetBSD 10.0, OpenBSD 7.5, Minix 3.1.8, AIX 5.1, HP-UX 11, Solaris 11.4, Cygwin 3.2.x, mingw, MSVC 14, Android API level 29.
@end itemize
