@node pthread_rwlockattr_init
@section @code{pthread_rwlockattr_init}
@findex pthread_rwlockattr_init

POSIX specification:@* @url{http://www.opengroup.org/onlinepubs/9699919799/functions/pthread_rwlockattr_init.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Minix 3.1.8, HP-UX 11, OSF/1 4.0, Solaris 2.6, mingw, MSVC 9, BeOS.
@end itemize
