@node pthread_sigmask
@section @code{pthread_sigmask}
@findex pthread_sigmask

POSIX specification:@* @url{http://www.opengroup.org/onlinepubs/9699919799/functions/pthread_sigmask.html}

Gnulib module: pthread_sigmask

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Minix 3.1.8, Solaris 2.4, mingw, MSVC 9, BeOS.
@item
This function is declared in @code{<pthread.h>} instead of @code{<signal.h>}
on some platforms:
Mac OS X 10.3, FreeBSD 6.4, OpenBSD 3.8, OSF/1 4.0, Solaris 2.6.
@item
This function does nothing and always returns 0 in programs that are not
linked with @code{-lpthread} on some platforms:
FreeBSD 6.4, HP-UX 11.31, Solaris 9.
@item
When it fails, this functions returns @minus{}1 instead of the error number on
some platforms:
Cygwin 1.7.5.
@item
This function does not immediately raise signals that were pending before
the call and unblocked by the call on some platforms:
IRIX 6.5.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
On platforms that do not natively support this function,
it has unspecified behavior in a multi-threaded process.
@end itemize
