@node pthread_attr_getstack
@section @code{pthread_attr_getstack}
@findex pthread_attr_getstack

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_attr_getstack.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Minix 3.1.8, AIX 5.1, HP-UX 11.11, IRIX 6.5, Solaris 9, Cygwin 1.7.9, mingw, MSVC 14.
@end itemize
