@node ptsname
@section @code{ptsname}
@findex ptsname

POSIX specification: @url{http://www.opengroup.org/onlinepubs/9699919799/functions/ptsname.html}

Gnulib module: ptsname

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
MacOS X 10.3, OpenBSD 3.8, mingw, BeOS.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
