@node putenv
@section @code{putenv}
@findex putenv

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/putenv.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize

Extension: Gnulib provides a module @samp{putenv} that substitutes a
@code{putenv} implementation that can also be used to remove environment
variables.
