@node pwrite
@section @code{pwrite}
@findex pwrite

POSIX specification:@* @url{http://www.opengroup.org/onlinepubs/9699919799/functions/pwrite.html}

Gnulib module: pwrite

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
HP-UX 10, mingw, BeOS.
@item
This function does not fail when an invalid (negative) offset is passed when
large file support is enabled on some platforms:
HP-UX 11.11.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
