@node rand_r
@section @code{rand_r}
@findex rand_r

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/rand_r.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Minix 3.1.8, mingw, MSVC 14, Android 4.4.
@item
POSIX says this function is obsolescent and it is planned to be
removed in POSIX 202x.
Use the function @code{random_r} from Gnulib module @code{random_r} instead.
@end itemize
