@node rand
@section @code{rand}
@findex rand

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/rand.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is only defined as an inline function on some platforms:
Android 4.4.
@end itemize
