@node rand
@subsection @code{rand}
@findex rand

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9799919799/functions/rand.html}

Gnulib module: rand
@mindex rand

Portability problems fixed by Gnulib:
@itemize
@item
This function crashes when used in multithreaded programs on some platforms:
CheriBSD.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is only defined as an inline function on some platforms:
Android 4.4.
@item
This function is not multithread-safe on some platforms:
musl libc, macOS 14, FreeBSD 13.2, NetBSD 10.0, AIX 7.1, Solaris 11.4.
@end itemize
