@node readlink
@section @code{readlink}
@findex readlink

POSIX specification: @url{http://www.opengroup.org/onlinepubs/9699919799/functions/readlink.html}

Gnulib module: readlink

Portability problems fixed by Gnulib:
@itemize
@item
Some platforms mistakenly succeed on @code{readlink("link/",buf,len)}:
Solaris 9.
@item
On some platforms, @code{readlink} returns @code{int} instead of
@code{ssize_t}:
FreeBSD 6.0, OpenBSD 3.8, Cygwin 1.5.x.
@item
This function is missing on some platforms:
mingw.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
When @code{readlink} is called on a directory: In the case of NFS mounted
directories, Cygwin sets @code{errno} to @code{ENOENT} or @code{EIO} instead of
@code{EINVAL}.  To avoid this problem, check for a directory before calling
@code{readlink}.
@item
When @code{readlink} is called on a file that is not a symbolic link:
Irix may set @code{errno} to @code{ENXIO} instead of @code{EINVAL}.  Cygwin
may set errno to @code{EACCES} instead of @code{EINVAL}.
@end itemize
