@node regexec
@section @code{regexec}
@findex regexec

POSIX specification:@* @url{http://www.opengroup.org/onlinepubs/9699919799/functions/regexec.html}

Gnulib module: regex

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
mingw, MSVC 9.
@item
Many regular expression implementations have bugs.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
