@node regexec
@section @code{regexec}
@findex regexec

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/regexec.html}

LSB specification:@* @url{https://refspecs.linuxbase.org/LSB_5.0.0/LSB-Core-generic/LSB-Core-generic/baselib-regexec-2.html}

Gnulib module: regex

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
mingw, MSVC 14.
@item
Many regular expression implementations have bugs.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
