@node regfree
@section @code{regfree}
@findex regfree

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/regfree.html}

Gnulib module: regex

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
mingw, MSVC 14.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
