@node remainder
@section @code{remainder}
@findex remainder

POSIX specification:@* @url{http://www.opengroup.org/onlinepubs/9699919799/functions/remainder.html}

Gnulib module: remainder

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
MSVC 9.
@item
This function is not declared on some platforms:
IRIX 5.3.
@end itemize
