@node remainderl
@section @code{remainderl}
@findex remainderl

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/remainderl.html}

Gnulib module: remainderl or remainderl-ieee

Portability problems fixed by either Gnulib module @code{remainderl} or @code{remainderl-ieee}:
@itemize
@item
This function is missing on some platforms:
FreeBSD 6.0, NetBSD 9.0, OpenBSD 3.8, Minix 3.1.8, AIX 5.1, HP-UX 11, older IRIX 6.5, Solaris 9, Cygwin 1.7.x, MSVC 9, Android 4.4.
@item
This function is not declared on some platforms:
IRIX 6.5.
@item
This function returns completely wrong values on some platforms:
OpenBSD 5.1/SPARC.
@item
This function produces results which are accurate to only 16 digits on some
platforms:
musl libc 1.2.2/arm64, musl libc 1.2.2/s390x.
@end itemize

Portability problems fixed by Gnulib module @code{remainderl-ieee}:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
