@node rename
@section @code{rename}
@findex rename

POSIX specification: @url{http://www.opengroup.org/onlinepubs/9699919799/functions/rename.html}

Gnulib module: rename

Portability problems fixed by Gnulib:
@itemize
@item
This function does not handle trailing slashes correctly on
some platforms (the full rules for trailing slashes are complex):
SunOS 4.1, mingw.
@item
This function will not replace an existing destination on some
platforms:
mingw.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
This function will not replace a destination that is currently opened
by any process:
mingw.
@item
This function mistakenly allows names ending in @samp{.} or @samp{..}
on some platforms:
Cygwin 1.5.x.
@end itemize
