@node rewinddir
@subsection @code{rewinddir}
@findex rewinddir

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9799919799/functions/rewinddir.html}

Gnulib module: rewinddir
@mindex rewinddir

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
MSVC 14.
@item
On Mac OS X platforms where @code{long int} is a 32-bit type, this function may
not work correctly on huge directories 2 GiB and larger.
@xref{Large File Support}.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
