@node rewinddir
@section @code{rewinddir}
@findex rewinddir

POSIX specification: @url{http://www.opengroup.org/onlinepubs/9699919799/functions/rewinddir.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
