@node rint
@subsection @code{rint}
@findex rint

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9799919799/functions/rint.html}

Gnulib module: rint or rint-ieee
@mindex rint
@mindex rint-ieee

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
MSVC 9.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
