@node rint
@section @code{rint}
@findex rint

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/rint.html}

Gnulib module: rint

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
MSVC 9.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
