@node rintl
@section @code{rintl}
@findex rintl

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/rintl.html}

Gnulib module: rintl

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
FreeBSD 6.0, NetBSD 5.0, OpenBSD 3.8, Minix 3.1.8, AIX 5.1, HP-UX 11, IRIX 6.5, Solaris 9, Cygwin 1.5.x, MSVC 9, Android 4.4.
@item
This function produces wrong results for negative numbers on some platforms:
NetBSD 8.0.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
