@node roundl
@section @code{roundl}
@findex roundl

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/roundl.html}

Gnulib module: roundl or roundl-ieee

Portability problems fixed by either Gnulib module @code{roundl} or @code{roundl-ieee}:
@itemize
@item
This function is missing on some platforms:
FreeBSD 5.2.1, NetBSD 5.0, OpenBSD 3.8, Minix 3.1.8, AIX 5.1, HP-UX 11, older IRIX 6.5, Solaris 9, Cygwin 1.7.x, MSVC 9.
@item
This function is not declared on some platforms:
glibc 2.8, IRIX 6.5.
@end itemize

Portability problems fixed by Gnulib module @code{roundl-ieee}:
@itemize
@item
This function returns a positive zero for an argument between @minus{}0.5 and 0
on some platforms:
AIX 7.1.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
