@node scalbn
@section @code{scalbn}
@findex scalbn

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/scalbn.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
AIX 5.1, IRIX 6.5, MSVC 9.
@end itemize
