@node scandir
@section @code{scandir}
@findex scandir

POSIX specification:@* @url{http://www.opengroup.org/onlinepubs/9699919799/functions/scandir.html}

Gnulib module: scandir

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Minix 3.1.8, Solaris 9, mingw, MSVC 9, BeOS.
@item
On platforms where @code{off_t} is a 32-bit type, this function may not
work correctly on huge directories larger than 2 GB.  Also, on platforms
where @code{ino_t} is a 32-bit type, this function may report inode numbers
incorrectly.  (Cf. @code{AC_SYS_LARGEFILE}.)
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
The fourth parameter of this function is declared as @code{int (*) (const void *, const void *)} on some platforms:
glibc 2.3.6, Mac OS X 10.5, FreeBSD 6.0, NetBSD 5.0, OpenBSD 3.8, Interix 3.5.
@item
The fourth parameter of this function is declared as @code{int (*) (void *, void *)} on some platforms:
AIX 5.1.
@end itemize
