@node secure_getenv
@subsection @code{secure_getenv}
@findex secure_getenv

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9799919799/functions/secure_getenv.html}

Documentation:
@itemize
@item
@ifinfo
@ref{Environment Access,,Environment Access,libc},
@end ifinfo
@ifnotinfo
@url{https://www.gnu.org/software/libc/manual/html_node/Environment-Access.html},
@end ifnotinfo
@item
@uref{https://www.kernel.org/doc/man-pages/online/pages/man3/secure_getenv.3.html,,man secure_getenv}.
@end itemize

Gnulib module: secure_getenv
@mindex secure_getenv

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on many non-glibc platforms:
glibc 2.16, macOS 14, FreeBSD 13.2, NetBSD 10.0, OpenBSD 5.2, Minix 3.2.0, AIX 7.1, HP-UX 11, Solaris 11.3, Cygwin 3.0, mingw, MSVC 14, Android 9.0.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
