@node sem_unlink
@section @code{sem_unlink}
@findex sem_unlink

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/sem_unlink.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Minix 3.1.8, Cygwin 1.5.x, mingw, MSVC 14.
@end itemize
