@node sendto
@section @code{sendto}
@findex sendto

POSIX specification:@* @url{http://www.opengroup.org/onlinepubs/9699919799/functions/sendto.html}

Gnulib module: sendto

Portability problems fixed by Gnulib:
@itemize
@item
This function has the return type @code{int} instead of @code{ssize_t}
on some platforms:
OSF/1 5.1.
@item
On Windows platforms (excluding Cygwin), error codes for @code{sendto}
are not placed in @code{errno}, and @code{WSAGetLastError} must be
used instead.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
