@node seteuid
@section @code{seteuid}
@findex seteuid

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/seteuid.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
HP-UX 11.23, mingw, MSVC 14.
@end itemize
