@node setgrent
@section @code{setgrent}
@findex setgrent

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/setgrent.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
mingw, MSVC 14, Android 7.1.
@end itemize
