@node setitimer
@section @code{setitimer}
@findex setitimer

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/setitimer.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
mingw, MSVC 14.
@item
POSIX says this function is obsolescent and it is planned to be
removed in POSIX 202x.
Use the functions @code{timer_create} and @code{timer_settime} instead.
@end itemize
