@node setpgrp
@section @code{setpgrp}
@findex setpgrp

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/setpgrp.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Minix 3.1.8, mingw, MSVC 14.
@item
POSIX says this function is obsolescent and it is planned to be
removed in POSIX 202x.
Use the function @code{setpgid} or @code{setsid} instead, as appropriate.
@end itemize
