@node setsockopt
@section @code{setsockopt}
@findex setsockopt

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/setsockopt.html}

LSB specification:@* @url{https://refspecs.linuxbase.org/LSB_5.0.0/LSB-Core-generic/LSB-Core-generic/baselib-setsockopt-2.html}

Gnulib module: setsockopt

Portability problems fixed by Gnulib:
@itemize
@item
On Windows platforms (excluding Cygwin), error codes from this function
are not placed in @code{errno}, and @code{WSAGetLastError} must be used
instead.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
Many socket options are not available on all platforms.
@end itemize
