@node setstate
@section @code{setstate}
@findex setstate

POSIX specification:@* @url{http://www.opengroup.org/onlinepubs/9699919799/functions/setstate.html}

Gnulib module: random

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Solaris 2.4, mingw, MSVC 9.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function has a slightly incompatible declaration (the argument type being
@samp{const char *} instead of @samp{char *}) on some platforms.
@end itemize
