@node shutdown
@section @code{shutdown}
@findex shutdown

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/shutdown.html}

Gnulib module: shutdown

Portability problems fixed by Gnulib:
@itemize
@item
On Windows platforms (excluding Cygwin), error codes from this function
are not placed in @code{errno}, and @code{WSAGetLastError} must be used
instead.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
