@node sigfillset
@subsection @code{sigfillset}
@findex sigfillset

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9799919799/functions/sigfillset.html}

Gnulib module: sigprocmask
@mindex sigprocmask

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
mingw, MSVC 14, Android 4.4.
@item
This function cannot be called from plain inline or extern inline functions
on some platforms:
macOS 10.8.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
