@node siginterrupt
@section @code{siginterrupt}
@findex siginterrupt

POSIX specification:@* @url{http://www.opengroup.org/onlinepubs/9699919799/functions/siginterrupt.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Minix 3.1.8, IRIX 5.3, Solaris 2.5.1, mingw, MSVC 9, Interix 3.5, BeOS.
@end itemize

Note: POSIX recommends using @code{sigaction} with SA_RESTART instead of
@code{siginterrupt (sig, 0)}.
