@node siginterrupt
@section @code{siginterrupt}
@findex siginterrupt

POSIX specification: @url{http://www.opengroup.org/susv3xsh/siginterrupt.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Solaris 2.5.1, mingw, Interix 3.5, BeOS.

@item
POSIX recommends using @code{sigaction} with SA_NODEFER instead.
@end itemize
