@node signgam
@section @code{signgam}
@findex signgam

POSIX specification:@* @url{http://www.opengroup.org/onlinepubs/9699919799/functions/signgam.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This variable is missing on some platforms:
Mac OS X 10.5, Minix 3.1.8, AIX 5.1, IRIX 6.5, OSF/1 5.1, mingw, MSVC 9.
@end itemize
