@node sigwait
@section @code{sigwait}
@findex sigwait

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/sigwait.html}

Gnulib module: extensions

Portability problems fixed by Gnulib:
@itemize
@item
This function has an incompatible declaration on some platforms:
Solaris 11.4 (when @code{_POSIX_PTHREAD_SEMANTICS} is not defined).
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Minix 3.1.8, mingw, MSVC 14.
@item
On Linux/glibc platforms before the advent of NPTL, signals could only be
sent to one particular thread.  In POSIX, signals are sent to the entire
process and executed by any thread of the process that happens to have the
particular signal currently unblocked.
@end itemize
