@node sinh
@subsection @code{sinh}
@findex sinh

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9799919799/functions/sinh.html}

Gnulib module: sinh
@mindex sinh

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
