@node sqrt
@subsection @code{sqrt}
@findex sqrt

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9799919799/functions/sqrt.html}

Gnulib module: sqrt or sqrt-ieee
@mindex sqrt
@mindex sqrt-ieee

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
