@node sqrt
@section @code{sqrt}
@findex sqrt

POSIX specification:@* @url{http://www.opengroup.org/onlinepubs/9699919799/functions/sqrt.html}

Gnulib module: sqrt

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Mac OS X 10.3.
@end itemize
