@node stdc_first_trailing_one
@subsection @code{stdc_first_trailing_one}
@findex stdc_first_trailing_one

Documentation:@*
ISO C23 (latest free draft
@url{https://www.open-std.org/jtc1/sc22/wg14/www/docs/n3220.pdf})
section 7.18.10.

Gnulib module: stdc_first_trailing_one
@mindex stdc_first_trailing_one

Portability problems fixed by Gnulib:
@itemize
@item
This macro is missing on many platforms:
glibc 2.38, macOS 14, FreeBSD 14.0, NetBSD 10.0, OpenBSD 7.5, AIX 7.3.1, HP-UX 11.31, Solaris 11.4, Cygwin 3.5.3, mingw, MSVC 17, Android 15.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
