@node stderr
@section @code{stderr}
@findex stderr

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/stderr.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
stderr is created in 32-bit mode instead of 64-bit mode: Cygwin 1.5.x.
One workaround is to use freopen(NULL, ``r+'', stderr) on Cygwin 1.5.21
or newer.  Another is to use the gnulib @code{ftello} module and do
ftello(stderr).
@item
POSIX states that a setuid application can guarantee that fd 2 is
open, but some systems guarantee this even for non-setuid programs.
If an application is executed with fd 2 closed, use of @code{stderr}
can affect an unrelated file that happened to be assigned to fd 2.
The gnulib *-safer modules may be used to guarantee that fd 2 stays
reserved for @code{stderr}.
@end itemize
