@node strcasecmp
@section @code{strcasecmp}
@findex strcasecmp

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/strcasecmp.html}

Gnulib module: strcase

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
MSVC 14.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function cannot work correctly on character strings in multibyte locales.
Gnulib provides an alternative function @code{mbscasecmp} that does a case
insensitive comparison of character strings and that works in all locales.
@end itemize
