@node strftime
@section @code{strftime}
@findex strftime

POSIX specification: @url{http://www.opengroup.org/susv3xsh/strftime.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
Windows does support the non-SUS %e specifier (and possibly the other
non-SUS specifiers too).
@end itemize

Extension: Gnulib offers a module @samp{strftime} that provides an
@code{strftime} function with various GNU extensions.
