@node strlcpy
@section @code{strlcpy}
@findex strlcpy

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/<2024>/functions/strlcpy.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
glibc 2.37, AIX 7.3.1, HP-UX 11.31, mingw, MSVC 14.
@end itemize
