@node strncmp
@subsection @code{strncmp}
@findex strncmp

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9799919799/functions/strncmp.html}

Gnulib module: strncmp
@mindex strncmp

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
