@node strncasecmp
@subsection @code{strncasecmp}
@findex strncasecmp

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9799919799/functions/strncasecmp.html}

Gnulib module: strncasecmp
@mindex strncasecmp

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
MSVC 14.
@item
This function uses the case mappings of a wrong locale on some platforms:
Solaris 11.4,
@c https://sourceware.org/pipermail/cygwin/2025-February/257347.html
Cygwin 3.5.6.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function cannot work correctly on character strings in multibyte locales.
@mindex mbsncasecmp
@mindex mbspcasecmp
Gnulib provides alternative functions @code{mbsncasecmp} and @code{mbspcasecmp}
that do a case insensitive comparison of character strings and that work in all
locales.
@end itemize
