@node strrchr
@section @code{strrchr}
@findex strrchr

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/strrchr.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function cannot work correctly on character strings in some multibyte
locales.  Gnulib provides an alternative function @code{mbsrchr} that works
on character strings in all locales.
@end itemize
