@node strtoul
@section @code{strtoul}
@findex strtoul

POSIX specification:@* @url{http://www.opengroup.org/onlinepubs/9699919799/functions/strtoul.html}

Gnulib module: strtoul

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some old platforms.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
