@node strtoumax
@subsection @code{strtoumax}
@findex strtoumax

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9799919799/functions/strtoumax.html}

Gnulib module: strtoumax
@mindex strtoumax

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
OpenBSD 3.8, Minix 3.1.8, AIX 5.1, Solaris 9, MSVC 9.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is only defined as a macro on some platforms:
HP-UX 11.11.
@item
If no conversion could be performed, this function sets @code{errno}
to @code{EINVAL} on some platforms.  Portable programs should check
for no conversion by comparing @code{str} to @code{*endptr}, not by
inspecting @code{errno}.
@end itemize
