@node strtoull
@section @code{strtoull}
@findex strtoull

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/strtoull.html}

Gnulib module: strtoull

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
HP-UX 11.11, MSVC 9.
@item
This function does not parse the leading @samp{0} when the input string is
@code{"0x"} and the base is 16 or 0 on some platforms:
Minix 3.3, mingw, MSVC 14.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
