@node strxfrm
@section @code{strxfrm}
@findex strxfrm

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/strxfrm.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
