@node swprintf
@section @code{swprintf}
@findex swprintf

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/swprintf.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
NetBSD 3.0, OpenBSD 3.8, Minix 3.1.8, HP-UX 11.00, IRIX 6.5, Cygwin 1.5.x.
@item
This function has a different signature on some platforms:
MSVC 9.
@item
This function is only defined as a macro on some platforms:
MSVC 14.
@item
This function does not support the @samp{n} directive on some platforms:
glibc when used with @code{_FORTIFY_SOURCE >= 2} (set by default on Ubuntu),
macOS 11.1, MSVC 14.
@item
This function sometimes returns a wrong value through the @samp{n} directive
on some platforms:
@c https://www.openwall.com/lists/musl/2023/03/19/1
musl libc 1.2.3.
@item
On Windows and 32-bit AIX platforms, @code{wchar_t} is a 16-bit type and therefore cannot
accommodate all Unicode characters.
@item
On Windows, this function does not take a buffer size as second argument.
@item
This function ignores the minimum field width in the @samp{lc} directive
on some platforms:
@c https://www.openwall.com/lists/musl/2023/03/20/1
musl libc 1.2.3.
@item
This function is broken when it produces output that contains null wide
characters on some platforms:
@c https://www.openwall.com/lists/musl/2023/03/22/9
musl libc 1.2.3,
FreeBSD 13.1, NetBSD 9.0, OpenBSD 7.2, macOS 12.5, AIX 7.2,
mingw.
@item
This function does not support the @samp{b} directive, required by ISO C23,
on some platforms:
glibc 2.34, musl libc, macOS 12.5, FreeBSD 13.1, NetBSD 9.0, OpenBSD 7.2,
AIX 7.2, HP-UX 11, Solaris 11.4, Cygwin 2.9.0, mingw, MSVC 14.
@item
The @code{%m} directive is not portable, use @code{%s} mapped to an
argument of @code{strerror(errno)} (or a version of @code{strerror_r})
instead.
@item
When formatting an integer with grouping flag, this function inserts thousands
separators even in the "C" locale on some platforms:
NetBSD 5.1.
@end itemize
