@node symlink
@subsection @code{symlink}
@findex symlink

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9799919799/functions/symlink.html}

Gnulib module: symlink
@mindex symlink

Portability problems fixed by Gnulib:
@itemize
@item
On some systems, @code{symlink(value,"name/")} mistakenly creates a
symlink:
macOS 14, FreeBSD 7.2, AIX 7.1, Solaris 9.
@item
This function is missing on some platforms; however, the replacement
always fails with @code{EPERM}:
mingw, MSVC 14.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
Some file systems do not support symbolic links.
@item
If the target is the empty string, this function can create an empty
symbolic link instead of failing with @code{ENOENT} as GNU/Linux does:
FreeBSD 14.0, NetBSD 10.0, OpenBSD 7.8, Solaris 11.4.
On Solaris, the empty symbolic link @code{""} resolves like @code{"."} does;
on the other operating systems, resolution fails with @code{ENOENT}.
@end itemize
