@node tan
@subsection @code{tan}
@findex tan

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9799919799/functions/tan.html}

Gnulib module: tan
@mindex tan

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
