@node tanh
@subsection @code{tanh}
@findex tanh

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9799919799/functions/tanh.html}

Gnulib module: tanh
@mindex tanh

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
