@node tanl
@section @code{tanl}
@findex tanl

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/tanl.html}

Gnulib module: tanl

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
FreeBSD 6.0, NetBSD 5.0, OpenBSD 3.8, Minix 3.1.8, HP-UX 11, IRIX 6.5, Solaris 9, Cygwin 1.7.x, Android 4.4.
@item
This function is only defined as a macro with arguments on some platforms:
MSVC 14.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
