@node tcflush
@section @code{tcflush}
@findex tcflush

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/tcflush.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
mingw, MSVC 14, Android 4.4.
@item
On some platforms, @code{tcflush} of @code{TCIFLUSH} on a non-tty fails with
errno set to @code{EINVAL} rather than @code{ENOTTY}.
@item
On some platforms, @code{tcflush} of @code{TCOFLUSH} on a non-tty fails with
errno set to @code{EINVAL} or, on IRIX, also @code{ENOSYS}, or, on Mac OS X,
also @code{EOPNOTSUPP} or @code{ENODEV}, rather than @code{ENOTTY}.
@end itemize
