@node tfind
@section @code{tfind}
@findex tfind

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/tfind.html}

Gnulib module: tsearch

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Minix 3.1.8, mingw, MSVC 14, Android 4.0.4.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
