@node timer_getoverrun
@section @code{timer_getoverrun}
@findex timer_getoverrun

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/timer_getoverrun.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Mac OS X 10.11, FreeBSD 6.0, Minix 3.1.8, Cygwin 2.9, mingw, MSVC 14.
@end itemize
