@node timespec_get
@subsection @code{timespec_get}
@findex timespec_get

ISO C23 specification:@* @url{https://www.open-std.org/jtc1/sc22/wg14/www/docs/n3220.pdf} section 7.29.2.6

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9799919799/functions/timespec_get.html}

Gnulib module: timespec_get
@mindex timespec_get

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on many platforms:
glibc 2.15, macOS 10.14, FreeBSD 11.0, NetBSD 7.1, OpenBSD 6.0, Minix 3.1.8, AIX 7.1, HP-UX 11.31, Solaris 11.3, Cygwin 3.5.x, mingw with MSVCRT, MSVC 14, Android 9.0.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
