@node tmpfile
@section @code{tmpfile}
@findex tmpfile

POSIX specification: @url{http://www.opengroup.org/onlinepubs/9699919799/functions/tmpfile.html}

Gnulib module: tmpfile

Portability problems fixed by Gnulib:
@itemize
@item
This function often fails for trivial reasons on some platforms:
mingw.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
