@node tmpnam
@section @code{tmpnam}
@findex tmpnam

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/tmpnam.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is not appropriate for creating temporary files.  (It has
security risks.)  Better use @code{mkstemp} instead.
@end itemize
