@node towlower
@section @code{towlower}
@findex towlower

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/towlower.html}

Gnulib module: wctype-h

Portability problems fixed by Gnulib:
@itemize
@item
This function returns values of which the upper 16 bits are incorrect
on some platforms:
mingw.
@item
This function cannot be called from plain inline or extern inline functions
on some platforms:
OS X 10.8.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
On Windows and 32-bit AIX platforms, @code{wchar_t} is a 16-bit type and therefore cannot
accommodate all Unicode characters.
@end itemize
