@node trunc
@section @code{trunc}
@findex trunc

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/trunc.html}

Gnulib module: trunc or trunc-ieee

Portability problems fixed by either Gnulib module @code{trunc} or @code{trunc-ieee}:
@itemize
@item
This function is missing on some platforms:
FreeBSD 5.2.1, NetBSD 3.0, OpenBSD 3.8, Solaris 9, MSVC 9.
@item
This function is not declared (without @code{-D_GNU_SOURCE}) on some platforms:
glibc 2.8.
@end itemize

Portability problems fixed by Gnulib module @code{trunc-ieee}:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
