@node trunc
@section @code{trunc}
@findex trunc

POSIX specification: @url{http://www.opengroup.org/onlinepubs/9699919799/functions/trunc.html}

Gnulib module: trunc

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
FreeBSD 5.2.1, NetBSD 3.0, OpenBSD 3.8, Solaris 9, Interix 3.5.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
