@node uselocale
@subsection @code{uselocale}
@findex uselocale

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9799919799/functions/uselocale.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on many platforms:
@c For NetBSD, see https://mail-index.netbsd.org/tech-userlevel/2015/12/29/msg009556.html
FreeBSD 9.0, NetBSD 10.0, OpenBSD 6.1, Minix 3.1.8, AIX 6.1, HP-UX 11, Solaris 11.3, Cygwin 2.5.x, mingw, MSVC 14, Android API level 20.
@item
This function is not documented and leads to crashes in subsequent
@code{setlocale} invocations on some platforms:
AIX 7.2.
@item
This function is useless because the @code{locale_t} type is not defined
on some platforms:
z/OS.
@item
This function is useless because the @code{locale_t} type contains basically
no information on some platforms:
OpenBSD 7.4.
@end itemize
