@node utime
@section @code{utime}
@findex utime

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/utime.html}

Gnulib module: utime

Portability problems fixed by Gnulib:
@itemize
@item
The times that are set on the file are affected by the current time zone and
by the DST flag of the current time zone on some platforms:
mingw, MSVC 14 (when the environment variable @code{TZ} is set).
@item
On some platforms, the prototype for @code{utime} omits @code{const}
for the second argument:
mingw, MSVC 14.
@item
On some platforms, @code{utime("link-to-file/",buf)} succeeds instead
of failing with @code{ENOTDIR}.
macOS 11.1.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
On some platforms, this function mis-handles a trailing slash:
Solaris 9.
@item
This function cannot set full timestamp resolution.  Use
@code{utimensat(AT_FDCWD,file,times,0)}, or the gnulib module @code{utimens},
instead.
@end itemize
