@node utime
@section @code{utime}
@findex utime

POSIX specification:@* @url{http://www.opengroup.org/onlinepubs/9699919799/functions/utime.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
On some old platforms (Sequent), @code{utime (file, NULL)} fails to set the
file's timestamp to the current time.
@item
On some platforms, this function mis-handles trailing slash:
Solaris 9.
@item
This function cannot set full timestamp resolution.  Use
@code{utimensat(AT_FDCWD,file,times,0)}, or the gnulib module utimens,
instead.
@item
On some platforms, the prototype for @code{utime} omits @code{const}
for the second argument.  Fortunately, the argument is not modified,
so it is safe to cast away const:
mingw, MSVC 9.
@end itemize
