@node va_copy
@subsection @code{va_copy}
@findex va_copy

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9799919799/functions/va_copy.html}

Gnulib module: stdarg-h
@mindex stdarg-h

Portability problems fixed by Gnulib:
@itemize
@item
This macro is missing on some platforms:
AIX 5.1 with cc or xlc, HP-UX 11 with cc.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
