@node va_copy
@section @code{va_copy}
@findex va_copy

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/va_copy.html}

Gnulib module: stdarg

Portability problems fixed by Gnulib:
@itemize
@item
This macro is missing on some platforms:
AIX 5.1 with cc or xlc, HP-UX 11 with cc, IRIX 6.5 with cc.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
