@node waitpid
@section @code{waitpid}
@findex waitpid

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/waitpid.html}

LSB specification:@* @url{https://refspecs.linuxbase.org/LSB_5.0.0/LSB-Core-generic/LSB-Core-generic/baselib-waitpid-3.html}

Gnulib module: waitpid

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
mingw, MSVC 14.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
