@node wcpncpy
@section @code{wcpncpy}
@findex wcpncpy

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/wcpncpy.html}

Gnulib module: wcpncpy

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Mac OS X 10.5, FreeBSD 6.0, NetBSD 9.0, OpenBSD 6.7, Minix 3.1.8, HP-UX 11,
IRIX 6.5, Solaris 10, Cygwin 1.5.x, mingw, MSVC 14.
@item
This function is not declared (without @code{-D_GNU_SOURCE}) on some platforms:
glibc 2.13.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
On Windows and 32-bit AIX platforms, @code{wchar_t} is a 16-bit type and therefore cannot
accommodate all Unicode characters.
@end itemize
