@node wcscspn
@section @code{wcscspn}
@findex wcscspn

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/wcscspn.html}

Gnulib module: wcscspn

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
On Windows and 32-bit AIX platforms, @code{wchar_t} is a 16-bit type and therefore cannot
accommodate all Unicode characters.
@end itemize
