@node wcsnlen
@section @code{wcsnlen}
@findex wcsnlen

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/wcsnlen.html}

Gnulib module: wcsnlen

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Mac OS X 10.5, FreeBSD 6.0, NetBSD 7.1, OpenBSD 6.7, Minix 3.1.8, HP-UX 11,
IRIX 6.5, Solaris 10, Cygwin 1.5.x, mingw.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
On Windows and 32-bit AIX platforms, @code{wchar_t} is a 16-bit type and therefore cannot
accommodate all Unicode characters.
@end itemize
