@node wcstombs
@section @code{wcstombs}
@findex wcstombs

POSIX specification:@* @url{http://www.opengroup.org/onlinepubs/9699919799/functions/wcstombs.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
On AIX and Windows platforms, @code{wchar_t} is a 16-bit type and therefore cannot
accommodate all Unicode characters.
@end itemize
