@node wctomb
@section @code{wctomb}
@findex wctomb

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/wctomb.html}

Gnulib module: wctomb

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Android 4.4.
@item
On Windows and 32-bit AIX platforms, @code{wchar_t} is a 16-bit type and therefore cannot
accommodate all Unicode characters.
@end itemize
