@node wctrans
@section @code{wctrans}
@findex wctrans

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9699919799/functions/wctrans.html}

Gnulib module: wctrans

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Minix 3.1.8, HP-UX 11.00, IRIX 6.5, mingw, MSVC 9, Android 7.1.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
On Windows and 32-bit AIX platforms, @code{wchar_t} is a 16-bit type and therefore cannot
accommodate all Unicode characters.
@end itemize
