@node wctype
@subsection @code{wctype}
@findex wctype

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9799919799/functions/wctype.html}

Gnulib module: wctype
@mindex wctype

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Minix 3.1.8, MSVC 9.
@item
This function is declared in @code{<wchar.h>}, not in @code{<wctype.h>}, on
some platforms:
HP-UX 11.00.
@item
This function does not support the @code{"blank"} character class
on some platforms:
mingw.
@item
The object returned by this function for the @code{"blank"} character class
is inconsistent with the @code{iswblank} and @code{isblank} functions
on some platforms:
MSVC 14.
@item
The object returned by this function for the @code{"punct"} character class
is inconsistent with the @code{ispunct} function on some platforms:
Android 11.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
On Windows and 32-bit AIX platforms, @code{wchar_t} is a 16-bit type and therefore cannot
accommodate all Unicode characters.
@mindex c32_get_type_test
However, the Gnulib function @code{c32_get_type_test}, provided by Gnulib
module @code{c32_get_type_test}, operates on 32-bit wide characters and
therefore does not have this limitation.
@end itemize
