@node wmemcmp
@subsection @code{wmemcmp}
@findex wmemcmp

POSIX specification:@* @url{https://pubs.opengroup.org/onlinepubs/9799919799/functions/wmemcmp.html}

Gnulib module: wmemcmp
@mindex wmemcmp

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
HP-UX 11.00, MSVC 14.
@item
This function compares the wide characters as if they were unsigned, although
@code{wchar_t} is signed, on some platforms:
glibc 2.14.1 on x86 or x86_64, musl libc 1.2.3, NetBSD 10.0, OpenBSD 7.2, Solaris 11.4.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
On Windows and 32-bit AIX platforms, @code{wchar_t} is a 16-bit type and therefore cannot
accommodate all Unicode characters.
@end itemize
