@node wordfree
@section @code{wordfree}
@findex wordfree

POSIX specification:@* @url{http://www.opengroup.org/onlinepubs/9699919799/functions/wordfree.html}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Mac OS X 10.3, OpenBSD 3.8, Minix 3.1.8, IRIX 5.3, Cygwin 1.5.x, mingw, MSVC 9, Interix 3.5, BeOS.
@end itemize
