@node adjtimex
@subsection @code{adjtimex}
@findex adjtimex

Documentation:
@itemize
@item
@ifinfo
@ref{High-Resolution Calendar,,High-Resolution Calendar,libc},
@end ifinfo
@ifnotinfo
@url{https://www.gnu.org/software/libc/manual/html_node/High_002dResolution-Calendar.html},
@end ifnotinfo
@item
@uref{https://www.kernel.org/doc/man-pages/online/pages/man2/adjtimex.2.html,,man adjtimex}.
@end itemize

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function exists only on Linux and is therefore
missing on many non-glibc platforms:
macOS 11.1, FreeBSD 13.0, NetBSD 9.0, OpenBSD 6.7, Minix 3.1.8, AIX 5.1, HP-UX 11, IRIX 6.5, Solaris 11.4, Cygwin 2.9, mingw, MSVC 14, Android 6.0.
@end itemize
