@node argz_append
@subsection @code{argz_append}
@findex argz_append

Gnulib module: argz

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Mac OS X 10.5, FreeBSD 6.0, NetBSD 5.0, OpenBSD 3.8, Minix 3.1.8, AIX 5.1, HP-UX 11,
IRIX 6.5, OSF/1 5.1, Solaris 11 2011-11, mingw, MSVC 9, Interix 3.5, BeOS.

@item
This function is broken on some platforms:
Cygwin 1.5.24.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
