@node copy_file_range
@subsection @code{copy_file_range}
@findex copy_file_range

Documentation:
@itemize
@item
@ifinfo
@ref{Copying File Data,,Copying data between two files,libc},
@end ifinfo
@ifnotinfo
@url{https://www.gnu.org/software/libc/manual/html_node/Copying-File-Data.html},
@end ifnotinfo
@item
@uref{https://www.kernel.org/doc/man-pages/online/pages/man2/copy_file_range.2.html,,man copy_file_range}.
@end itemize

Gnulib module: copy-file-range

Portability problems fixed by Gnulib:
@itemize
@item
This function exists only on Linux and FreeBSD and is therefore
missing on many non-glibc platforms:
glibc 2.26, macOS 11.1, FreeBSD 12.0, NetBSD 9.0, OpenBSD 6.7, Minix 3.1.8, AIX 7.1, HP-UX 11.31, IRIX 6.5, Solaris 11.4, Cygwin 2.9, mingw, MSVC 14, Android 9.0.
But the replacement function is only a stub: It always fails with error ENOSYS.

@item
This function has many problems on Linux kernel versions before 5.3.
On these kernel versions, the replacement function always fails with
error ENOSYS.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
