@node cuserid
@subsection @code{cuserid}
@findex cuserid

Documentation:
@itemize
@item
@ifinfo
@ref{Who Logged In,,Identifying Who Logged In,libc},
@end ifinfo
@ifnotinfo
@url{https://www.gnu.org/software/libc/manual/html_node/Who-Logged-In.html},
@end ifnotinfo
@item
@uref{https://www.kernel.org/doc/man-pages/online/pages/man3/cuserid.3.html,,man cuserid}.
@end itemize

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
macOS 11.1, FreeBSD 13.0, NetBSD 9.0, OpenBSD 6.7, mingw, MSVC 14, Android 9.0.
@end itemize
