@node dladdr
@subsection @code{dladdr}
@findex dladdr

LSB specification:@* @url{https://refspecs.linuxbase.org/LSB_5.0.0/LSB-Core-generic/LSB-Core-generic/baselib-dladdr-3.html}

Documentation:@* @uref{https://www.kernel.org/doc/man-pages/online/pages/man3/dladdr.3.html,,man dladdr}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Minix 3.1.8, AIX 5.1, IRIX 6.5, Cygwin 1.7.x, mingw, MSVC 14.
@end itemize
