@node dn_comp
@subsection @code{dn_comp}
@findex dn_comp

Documentation:@* @uref{https://www.kernel.org/doc/man-pages/online/pages/man3/dn_comp.3.html,,man dn_comp}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
macOS 11.1, OpenBSD 6.7, Minix 3.3.0, Cygwin 1.5.x, mingw, MSVC 14, Android 9.0.
@end itemize
