@node dngettext
@subsection @code{dngettext}
@findex dngettext

LSB specification:@* @url{https://refspecs.linuxbase.org/LSB_5.0.0/LSB-Core-generic/LSB-Core-generic/baselib-dngettext.html}

Documentation:
@itemize
@item
@ifinfo
@ref{Advanced gettext functions,,Additional functions for more complicated situations,libc},
@end ifinfo
@ifnotinfo
@url{https://www.gnu.org/software/libc/manual/html_node/Advanced-gettext-functions.html},
@end ifnotinfo
@item
@uref{https://www.kernel.org/doc/man-pages/online/pages/man3/dngettext.3.html,,man dngettext}.
@end itemize

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
macOS 11.1, FreeBSD 13.0, OpenBSD 6.7, Minix 3.1.8, HP-UX 11, IRIX 6.5, Cygwin 2.9, mingw, MSVC 14, Android 9.0.
@end itemize
