@node ether_line
@subsection @code{ether_line}
@findex ether_line

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
HP-UX 11, Cygwin, mingw, MSVC 9, Interix 3.5, BeOS.
@end itemize
