@node ether_aton
@subsection @code{ether_aton}
@findex ether_aton

Documentation:@* @uref{https://www.kernel.org/doc/man-pages/online/pages/man3/ether_aton.3.html,,man ether_aton}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
HP-UX 11, Cygwin 2.9, mingw, MSVC 14, Android 2.3.
@end itemize
