@node eventfd
@subsection @code{eventfd}
@findex eventfd

Documentation:@* @uref{https://www.kernel.org/doc/man-pages/online/pages/man2/eventfd.2.html,,man eventfd}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function exists only on Linux, FreeBSD, and illumos and is therefore
missing on many non-glibc platforms:
glibc 2.6, macOS 11.1, FreeBSD 12.0, NetBSD 9.0, OpenBSD 6.7, Minix 3.1.8, AIX 7.1, HP-UX 11.31, IRIX 6.5, Solaris 11.4, Cygwin 2.9, mingw, MSVC 14.
@end itemize
