@node flock
@subsection @code{flock}
@findex flock

Gnulib module: flock

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
mingw, MSVC 9
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
AIX 5.1, HP-UX 11.23, Solaris 11 2011-11, BeOS.
@end itemize
