@node futimes
@subsection @code{futimes}
@findex futimes

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Minix 3.1.8, AIX 5.1, HP-UX 11, IRIX 6.5, OSF/1 5.1, Solaris 11 2011-11, mingw, MSVC 9,
Interix 3.5, BeOS.
@item
This function cannot set full timestamp resolution.  Use
@code{futimens(fd,times)} instead.
@end itemize
