@node futimes
@subsection @code{futimes}
@findex futimes

LSB specification:@* @url{https://refspecs.linuxbase.org/LSB_5.0.0/LSB-Core-generic/LSB-Core-generic/baselib-futimes.html}

Documentation:
@itemize
@item
@ifinfo
@ref{File Times,,File Times,libc},
@end ifinfo
@ifnotinfo
@url{https://www.gnu.org/software/libc/manual/html_node/File-Times.html},
@end ifnotinfo
@item
@uref{https://www.kernel.org/doc/man-pages/online/pages/man3/futimes.3.html,,man futimes}.
@end itemize

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Minix 3.1.8, AIX 5.1, HP-UX 11, IRIX 6.5, Solaris 11.4, mingw, MSVC 14, Android 7.1.
@item
This function cannot set full timestamp resolution.  Use
@code{futimens(fd,times)} instead.
@end itemize
