@node futimesat
@subsection @code{futimesat}
@findex futimesat

Documentation:@* @uref{https://www.kernel.org/doc/man-pages/online/pages/man2/futimesat.2.html,,man futimesat}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
glibc 2.3.6, macOS 11.1, FreeBSD 6.0, NetBSD 9.0, OpenBSD 6.7, Minix 3.1.8, AIX 5.1, HP-UX 11, IRIX 6.5, Cygwin 1.5.x, mingw, MSVC 14, Android 7.1.
@item
On some platforms, this function mis-handles a trailing slash:
Solaris 9.
@item
This function cannot set full timestamp resolution.  Use

@example
file ? utimensat(fd, file, times, 0)
     : futimens(fd, times)
@end example

@noindent or the gnulib module @code{fdutimensat}, instead.
@end itemize
