@node get_phys_pages
@subsection @code{get_phys_pages}
@findex get_phys_pages

Documentation:
@itemize
@item
@ifinfo
@ref{Query Memory Parameters,,How to get information about the memory subsystem?,libc},
@end ifinfo
@ifnotinfo
@url{https://www.gnu.org/software/libc/manual/html_node/Query-Memory-Parameters.html},
@end ifnotinfo
@item
@uref{https://www.kernel.org/doc/man-pages/online/pages/man3/get_phys_pages.3.html,,man get_phys_pages}.
@end itemize

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on many non-glibc platforms:
macOS 11.1, FreeBSD 13.0, NetBSD 9.0, OpenBSD 6.7, Minix 3.1.8, AIX 5.1, HP-UX 11, IRIX 6.5, Solaris 11.4, Cygwin 1.7.1, mingw, MSVC 14, Android 5.1.
@end itemize
