@node get_nprocs_conf
@subsection @code{get_nprocs_conf}
@findex get_nprocs_conf

Documentation:
@itemize
@item
@ifinfo
@ref{Processor Resources,,Learn about the processors available,libc},
@end ifinfo
@ifnotinfo
@url{https://www.gnu.org/software/libc/manual/html_node/Processor-Resources.html},
@end ifnotinfo
@item
@uref{https://www.kernel.org/doc/man-pages/online/pages/man3/get_nprocs_conf.3.html,,man get_nprocs_conf}.
@end itemize

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on many non-glibc platforms:
macOS 11.1, FreeBSD 13.0, NetBSD 9.0, OpenBSD 6.7, Minix 3.1.8, AIX 5.1, HP-UX 11, IRIX 6.5, Solaris 10, Cygwin 1.7.1, mingw, MSVC 14, Android 5.1.
@end itemize
