@node getdtablesize
@subsection @code{getdtablesize}
@findex getdtablesize

Gnulib module: getdtablesize

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Android LP64, mingw, MSVC 9.

@item
This function is not declared on some platforms:
Android LP32.

@item
This function does not represent the true @code{RLIMIT_NOFILE} soft
limit on some platforms:
Android LP32, Cygwin 1.7.25.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
