@node getentropy
@subsection @code{getentropy}
@findex getentropy

Documentation:
@itemize
@item
@ifinfo
@ref{Unpredictable Bytes,,Generating Unpredictable Bytes,libc},
@end ifinfo
@ifnotinfo
@url{https://www.gnu.org/software/libc/manual/html_node/Unpredictable-Bytes.html},
@end ifnotinfo
@item
@uref{https://www.kernel.org/doc/man-pages/online/pages/man3/getentropy.3.html,,man getentropy}.
@end itemize

Gnulib module: getentropy

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
glibc 2.24, Mac OS X 10.11, FreeBSD 11.0, NetBSD 5.0, OpenBSD 3.8, Minix 3.1.8, AIX 7.1, HP-UX 11.31, IRIX 6.5, Solaris 11.0, Cygwin, mingw, MSVC 14, Android 9.0.
@item
This function is declared in @code{<sys/random.h>}, not in @code{<unistd.h>},
on some platforms:
Mac OS X 10.13, Solaris 11.4, Android 9.0.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize

Note: This function does not provides high-quality random numbers, as needed
by some crypto applications.  If you want such high-quality random numbers,
use the function @code{getrandom} with the @code{GRND_RANDOM} flag or (better)
use the @samp{crypto/gc-random} module and configure with
@samp{--with-libgcrypt}.
