@node getgrouplist
@subsection @code{getgrouplist}
@findex getgrouplist

LSB specification:@* @url{https://refspecs.linuxbase.org/LSB_5.0.0/LSB-Core-generic/LSB-Core-generic/baselib-getgrouplist-3.html}

Documentation:
@itemize
@item
@ifinfo
@ref{Setting Groups,,Setting the Group IDs,libc},
@end ifinfo
@ifnotinfo
@url{https://www.gnu.org/software/libc/manual/html_node/Setting-Groups.html},
@end ifnotinfo
@item
@uref{https://www.kernel.org/doc/man-pages/online/pages/man3/getgrouplist.3.html,,man getgrouplist}.
@end itemize

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function takes @code{int} instead of @code{gid_t} parameters
on some platforms: OS X 10.11.

@item
This function is missing on some platforms:
Minix 3.1.8, AIX 5.1, HP-UX 11, IRIX 6.5, Solaris 11.0, Cygwin 1.7.9, mingw, MSVC 14.
@end itemize

The Gnulib module @code{getugroups} provides a similar API.
