@node getgrouplist
@subsection @code{getgrouplist}
@findex getgrouplist

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function takes @code{int} instead of @code{gid_t} parameters
on some platforms: OS X 10.11.

@item
This function is missing on some platforms:
Minix 3.1.8, AIX 5.1, HP-UX 11, IRIX 6.5, OSF/1 5.1, Solaris 11 2011-11, Cygwin 1.7.9, mingw, MSVC 9, BeOS.
@end itemize

The Gnulib module @code{getugroups} provides a similar API.
