@node getw
@subsection @code{getw}
@findex getw

Documentation:
@itemize
@item
@ifinfo
@ref{Character Input,,Character Input,libc},
@end ifinfo
@ifnotinfo
@url{https://www.gnu.org/software/libc/manual/html_node/Character-Input.html},
@end ifnotinfo
@item
@uref{https://www.kernel.org/doc/man-pages/online/pages/man3/getw.3.html,,man getw}.
@end itemize

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Android 9.0.
@end itemize
