@node glob_pattern_p
@subsection @code{glob_pattern_p}
@findex glob_pattern_p

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on most non-glibc platforms:
macOS 11.1, FreeBSD 13.0, NetBSD 5.0, OpenBSD 6.7, Minix 3.1.8, AIX 5.1, HP-UX 11,
IRIX 6.5, Solaris 11.4, Cygwin 1.5.x, mingw, MSVC 14, Android 9.0.
@end itemize
