@node inet_net_ntop
@subsection @code{inet_net_ntop}
@findex inet_net_ntop

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
HP-UX 11, IRIX 6.5, OSF/1 4.0, Cygwin, mingw, Interix 3.5, BeOS.
@end itemize
