@node inet_network
@subsection @code{inet_network}
@findex inet_network

Documentation:
@itemize
@item
@ifinfo
@ref{Host Address Functions,,Host Address Functions,libc},
@end ifinfo
@ifnotinfo
@url{https://www.gnu.org/software/libc/manual/html_node/Host-Address-Functions.html},
@end ifnotinfo
@item
@uref{https://www.kernel.org/doc/man-pages/online/pages/man3/inet_network.3.html,,man inet_network}.
@end itemize

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
mingw, MSVC 14, Android 4.4.
@end itemize
