@node inet_makeaddr
@subsection @code{inet_makeaddr}
@findex inet_makeaddr

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Minix 3.1.8, mingw, MSVC 9, BeOS.
@end itemize
