@node isinff
@subsection @code{isinff}
@findex isinff

Documentation:
@itemize
@item
@ifinfo
@ref{Floating Point Classes,,Floating-Point Number Classification Functions,libc},
@end ifinfo
@ifnotinfo
@url{https://www.gnu.org/software/libc/manual/html_node/Floating-Point-Classes.html},
@end ifnotinfo
@item
@uref{https://www.kernel.org/doc/man-pages/online/pages/man3/isinff.3.html,,man isinff}.
@end itemize

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
macOS 11.1, FreeBSD 13.0, Minix 3.1.8, AIX 5.1, HP-UX 11, IRIX 6.5, Solaris 11.4, mingw, MSVC 14, Android 4.4.
@item
This function is not declared on some platforms:
Android 9.0.
@end itemize
