@node isnanf
@subsection @code{isnanf}
@findex isnanf

Gnulib module: isnanf

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Mac OS X 10.5, Minix 3.1.8, AIX 5.1, HP-UX 11, MSVC 9.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
