@node isnanl
@subsection @code{isnanl}
@findex isnanl

Documentation:
@itemize
@item
@ifinfo
@ref{Floating Point Classes,,Floating-Point Number Classification Functions,libc},
@end ifinfo
@ifnotinfo
@url{https://www.gnu.org/software/libc/manual/html_node/Floating-Point-Classes.html},
@end ifnotinfo
@item
@uref{https://www.kernel.org/doc/man-pages/online/pages/man3/isnanl.3.html,,man isnanl}.
@end itemize

Gnulib module: isnanl

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Mac OS X 10.5, FreeBSD 6.0, NetBSD 5.0, OpenBSD 3.8, Minix 3.1.8, AIX 5.1, HP-UX 11, IRIX 6.5, Cygwin, MSVC 14, Android 4.4.
@item
This function is not declared on some platforms:
Android 9.0.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
