@node lchmod
@subsection @code{lchmod}
@findex lchmod

Gnulib module: lchmod

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
OpenBSD 3.8, Minix 3.1.8, AIX 5.1, IRIX 6.5, Solaris 11.4, Cygwin, mingw, MSVC 14, Android 9.0.
@item
This function is not declared on some platforms:
HP-UX 11.31.
@item
This function always fails with @code{errno} set to @code{ENOSYS},
even when the file is not a symbolic link:
GNU/Linux with glibc 2.31.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
