@node llistxattr
@subsection @code{llistxattr}
@findex llistxattr

Documentation:@* @uref{https://www.kernel.org/doc/man-pages/online/pages/man2/llistxattr.2.html,,man llistxattr}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on many non-glibc platforms:
macOS 14, FreeBSD 14.0, NetBSD 5.0, OpenBSD 7.5, Minix 3.1.8, AIX 5.1, HP-UX 11, Solaris 11.4, Cygwin 1.5.x, mingw, MSVC 14, Android 4.0.4.
@item
This function fails with @code{EACCES} on unreadable files accessed via NFS:
Linux kernel 6.12.
@item
This function does not report synthetic @code{security.*} extended attributes
on @code{tmpfs} and @code{kernfs}-based file systems:
Linux kernel 6.14.
@item
This function can fail with @code{ERANGE} even if the buffer is large enough:
Linux kernel 6.15.
@end itemize
