@node lutimes
@subsection @code{lutimes}
@findex lutimes

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Mac OS X 10.4, OpenBSD 3.8, Minix 3.1.8, AIX 5.1, HP-UX 11, IRIX 6.5, OSF/1 5.1,
Solaris 11 2011-11, mingw, MSVC 9, Interix 3.5, BeOS.
@item
This function cannot set full timestamp resolution.  Use
@code{utimensat(AT_FDCWD,file,times,AT_SYMLINK_NOFOLLOW)}, or the
gnulib module utimens, instead.
@item
The mere act of using @code{lstat} modifies the access time of
symlinks on some platforms, so @code{lutimes} can only effectively
change modification time:
Cygwin.
@end itemize
