@node mallopt
@subsection @code{mallopt}
@findex mallopt

Documentation:
@itemize
@item
@ifinfo
@ref{Malloc Tunable Parameters,,Malloc Tunable Parameters,libc},
@end ifinfo
@ifnotinfo
@url{https://www.gnu.org/software/libc/manual/html_node/Malloc-Tunable-Parameters.html},
@end ifnotinfo
@item
@uref{https://www.kernel.org/doc/man-pages/online/pages/man3/mallopt.3.html,,man mallopt}.
@end itemize

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
macOS 11.1, FreeBSD 13.0, NetBSD 9.0, OpenBSD 6.7, Minix 3.1.8, IRIX 6.5, Solaris 11 2010-11, mingw, MSVC 14, Android 7.1.
@end itemize
