@node mincore
@subsection @code{mincore}
@findex mincore

Documentation:@* @uref{https://www.kernel.org/doc/man-pages/online/pages/man2/mincore.2.html,,man mincore}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
OpenBSD 7.9, Minix 3.1.8, AIX 5.1, HP-UX 11, Cygwin 2.9, mingw, MSVC 14.
@item
On Solaris 10 this function accepts @code{char *} not @code{void *},
unless you define feature test macros like @code{_POSIX_C_SOURCE}
or @code{_XOPEN_SOURCE} that may undesirably hide other symbols.
To work around this problem, callers can limit themselves to either
@code{void *} or @code{char *}.
@end itemize
