@node mkstemps
@subsection @code{mkstemps}
@findex mkstemps

Documentation:@* @uref{https://www.kernel.org/doc/man-pages/online/pages/man3/mkstemps.3.html,,man mkstemps}

Gnulib module: mkstemps

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on many non-glibc platforms:
glibc 2.10, Minix 3.1.8, AIX 5.1, HP-UX 11, IRIX 6.5, Solaris 10,
Cygwin 1.5.x, mingw, MSVC 14.
@item
This function is declared in @code{<unistd.h>} instead of @code{<stdlib.h>}
on some platforms:
macOS 11.1.
@item
On platforms where @code{off_t} is a 32-bit type, @code{mkstemps} may not work
correctly to create files larger than 2 GB@.  (Cf. @code{AC_SYS_LARGEFILE}.)
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize

The gnulib module @code{clean-temp} can create temporary files that will not
be left behind after signals such as SIGINT.
