@node pthread_getattr_np
@subsection @code{pthread_getattr_np}
@findex pthread_getattr_np

LSB specification:@* @url{https://refspecs.linuxbase.org/LSB_5.0.0/LSB-Core-generic/LSB-Core-generic/baselib-pthread-getattr-np-1.html}

Documentation:@* @uref{https://www.kernel.org/doc/man-pages/online/pages/man3/pthread_getattr_np.3.html,,man pthread_getattr_np}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on many non-glibc platforms:
macOS 11.1, FreeBSD 13.0, NetBSD 5.0, OpenBSD 6.7, Minix 3.1.8, AIX 5.1, HP-UX 11, IRIX 6.5, Solaris 11.3, Cygwin 1.7.9, mingw, MSVC 14.
@end itemize
