@node pthread_clockjoin_np
@subsection @code{pthread_clockjoin_np}
@findex pthread_clockjoin_np

Documentation:
@itemize
@item
@ifinfo
@ref{Default Thread Attributes,,Setting Process-wide defaults for thread attributes,libc}.
@end ifinfo
@ifnotinfo
@url{https://www.gnu.org/software/libc/manual/html_node/Default-Thread-Attributes.html}.
@end ifnotinfo
@c Not yet.
@c @item
@c @uref{https://www.kernel.org/doc/man-pages/online/pages/man3/pthread_clockjoin_np.3.html,,man pthread_clockjoin_np}.
@end itemize

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on all non-glibc platforms:
macOS 11.1, FreeBSD 13.0, NetBSD 9.0, OpenBSD 6.7, Minix 3.1.8, AIX 5.1, HP-UX 11, IRIX 6.5, Solaris 11.4, Cygwin 2.9, mingw, MSVC 14, Android 9.0.
@end itemize
