@node pthread_getaffinity_np
@subsection @code{pthread_getaffinity_np}
@findex pthread_getaffinity_np

Documentation:@* @uref{https://www.kernel.org/doc/man-pages/online/pages/man3/pthread_getaffinity_np.3.html,,man pthread_getaffinity_np}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on many non-glibc platforms:
glibc 2.3.2, macOS 14, FreeBSD 6.4, NetBSD 3.0, OpenBSD 7.5, Minix 3.1.8, AIX 7.1, HP-UX 11.31, Solaris 11.4, Cygwin 3.0.x, mingw, MSVC 14, Android API level 35.
@item
This function has a different signature on some platforms:
glibc 2.3.3.
@item
The third parameter has a different type on some platforms:
FreeBSD 14.0, NetBSD 10.0.
@end itemize
