@node pthread_getaffinity_np
@subsection @code{pthread_getaffinity_np}
@findex pthread_getaffinity_np

Documentation:@* @uref{https://www.kernel.org/doc/man-pages/online/pages/man3/pthread_getaffinity_np.3.html,,man pthread_getaffinity_np}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on many non-glibc platforms:
glibc 2.3.2, macOS 11.1, FreeBSD 6.4, NetBSD 3.0, OpenBSD 6.7, Minix 3.1.8, AIX 7.1, HP-UX 11.31, IRIX 6.5, Solaris 11.4, Cygwin 2.9, mingw, MSVC 14, Android 9.0.
@item
This function has a different signature on some platforms:
glibc 2.3.3.
@item
The third parameter has a different type on some platforms:
FreeBSD 13.0, NetBSD 9.0.
@end itemize
