@node ptrace
@subsection @code{ptrace}
@findex ptrace

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
AIX 5.1, Cygwin, mingw, MSVC 9, Interix 3.5, BeOS.
@end itemize
