@node quotactl
@subsection @code{quotactl}
@findex quotactl

Documentation:@* @uref{https://www.kernel.org/doc/man-pages/online/pages/man2/quotactl.2.html,,man quotactl}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Minix 3.1.8, AIX 5.1, Solaris 11.4, Cygwin 1.7.x, mingw, MSVC 14, Android 7.1.
@end itemize
