@node reallocarray
@subsection @code{reallocarray}
@findex reallocarray

Gnulib module: reallocarray

Allocate multiple memory locations of a fixed size with integer overflow
protection.
Glibc Manual: @url{https://www.gnu.org/software/libc/manual/html_node/Changing-Block-Size.html#Changing-Block-Size}

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on many platforms:
glibc 2.25, macOS 10.13, FreeBSD 10, NetBSD 7, OpenBSD 5.5, Minix 3.3.0,
AIX 7.2, HP-UX 11, IRIX, Solaris 11.4, Tru64, Cygwin, mingw,
MSVC 14, Interix, BeOS, Android 9.0.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
