@node res_mkquery
@subsection @code{res_mkquery}
@findex res_mkquery

Documentation:@* @uref{https://www.kernel.org/doc/man-pages/online/pages/man3/res_mkquery.3.html,,man res_mkquery}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
macOS 11.1, Cygwin 1.5.x, mingw, MSVC 14.
@end itemize
