@node rpc_createerr
@subsection @code{rpc_createerr}
@findex rpc_createerr

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This variable is missing on some platforms:
Minix 3.1.8, AIX 5.1, IRIX 6.5, Cygwin 2.9, mingw, MSVC 14, Android 9.0.
@end itemize
