@node rpmatch
@subsection @code{rpmatch}
@findex rpmatch

Documentation:
@itemize
@item
@ifinfo
@ref{Yes-orYes-or002dNo Questions,,Yes-or-No Questions,libc},
@end ifinfo
@ifnotinfo
@url{https://www.gnu.org/software/libc/manual/html_node/Yes_002dor_002dNo-Questions.html},
@end ifnotinfo
@item
@uref{https://www.kernel.org/doc/man-pages/online/pages/man3/rpmatch.3.html,,man rpmatch}.
@end itemize

Gnulib module: rpmatch
@mindex rpmatch

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
macOS 10.14, FreeBSD 5.2.1, NetBSD 10.0, OpenBSD 7.5, Minix 3.1.8, HP-UX 11, Solaris 11.4, Cygwin 1.7.x, mingw, MSVC 14, Android 9.0.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
