@node scandirat
@subsection @code{scandirat}
@findex scandirat

Documentation:@* @uref{https://www.kernel.org/doc/man-pages/online/pages/man3/scandirat.3.html,,man scandirat}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on many non-glibc platforms:
glibc 2.14, macOS 14, FreeBSD 13.0, NetBSD 10.0, OpenBSD 7.5, Minix 3.1.8, AIX 7.1, HP-UX 11.31, Solaris 11.4, Cygwin 1.7.10, mingw, MSVC 14, Android 6.0.
@end itemize
