@node sched_getcpu
@subsection @code{sched_getcpu}
@findex sched_getcpu

Documentation:@* @uref{https://www.kernel.org/doc/man-pages/online/pages/man3/sched_getcpu.3.html,,man sched_getcpu}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function exists only on Linux and is therefore
missing on most non-glibc platforms:
glibc 2.5, macOS 11.1, FreeBSD 13.0, NetBSD 9.0, OpenBSD 6.7, Minix 3.1.8, AIX 7.1, HP-UX 11.31, IRIX 6.5, Solaris 11.4, Cygwin 2.9, mingw, MSVC 14.
@end itemize
