@node sched_setattr
@subsection @code{sched_setattr}
@findex sched_setattr

Documentation:@* @uref{https://www.kernel.org/doc/man-pages/online/pages/man2/sched_setattr.2.html,,man sched_setattr}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function exists only on Linux and is therefore
missing on most non-glibc platforms:
glibc 2.40, macOS 14, FreeBSD 13.0, NetBSD 10.0, OpenBSD 7.5, Minix 3.1.8, AIX 7.1, HP-UX 11.31, Solaris 11.4, Cygwin 2.10.x, mingw, MSVC 14, Android API level 36.
@end itemize
