@node sendfile
@subsection @code{sendfile}
@findex sendfile

LSB specification:@* @url{https://refspecs.linuxbase.org/LSB_5.0.0/LSB-Core-generic/LSB-Core-generic/baselib-sendfile.html}

Documentation:@* @uref{https://www.kernel.org/doc/man-pages/online/pages/man2/sendfile.2.html,,man sendfile}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
NetBSD 9.0, OpenBSD 6.7, Minix 3.1.8, AIX 5.1, IRIX 6.5, Solaris 11 2010-11, Cygwin 2.9, mingw, MSVC 14, Android 4.4.
@item
On platforms where @code{off_t} is a 32-bit type, this function may not
work correctly on files larger than 2 GB@.  The fix is to use the
@code{AC_SYS_LARGEFILE} macro.
@end itemize
