@node sigabbrev_np
@subsection @code{sigabbrev_np}
@findex sigabbrev_np

Documentation:@*
@ifinfo
@ref{Signal Messages,,Signal Messages,libc}.
@end ifinfo
@ifnotinfo
@url{https://www.gnu.org/software/libc/manual/html_node/Signal-Messages.html}.
@end ifnotinfo

Gnulib module: sigabbrev_np

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on all non-glibc platforms:
glibc 2.31, macOS 11.1, FreeBSD 13.0, NetBSD 9.0, OpenBSD 6.7, Minix 3.1.8, AIX 7.1, HP-UX 11.31, IRIX 6.5, Solaris 11.4, Cygwin 2.9, mingw, MSVC 14, Android 9.0.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize

Note: Gnulib has a module @code{sig2str} that contains an equivalent function
and also one that does the opposite conversion, from an abbreviated signal name
to a signal number.
