@node strchrnul
@subsection @code{strchrnul}
@findex strchrnul

Documentation:
@itemize
@item
@ifinfo
@ref{Search Functions,,Search Functions,libc},
@end ifinfo
@ifnotinfo
@url{https://www.gnu.org/software/libc/manual/html_node/Search-Functions.html},
@end ifnotinfo
@item
@uref{https://www.kernel.org/doc/man-pages/online/pages/man3/strchrnul.3.html,,man strchrnul}.
@end itemize

Gnulib module: strchrnul

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on many non-glibc platforms:
macOS 11.1, FreeBSD 6.0, NetBSD 7.1, OpenBSD 6.7, Minix 3.1.8, AIX 5.1, HP-UX 11, IRIX 6.5, Solaris 10, Cygwin 1.7.8, mingw, MSVC 14, Android 6.0.
@item
This function crashes when no occurrence is found on some platforms:
Cygwin 1.7.9.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
