@node svcerr_noprog
@subsection @code{svcerr_noprog}
@findex svcerr_noprog

Documentation:@* @uref{https://www.kernel.org/doc/man-pages/online/pages/man3/svcerr_noprog.3.html,,man svcerr_noprog}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Minix 3.1.8, Cygwin 2.9, mingw, MSVC 14, Android 9.0.
@end itemize
