@node svctcp_create
@subsection @code{svctcp_create}
@findex svctcp_create

LSB specification:@* @url{https://refspecs.linuxbase.org/LSB_5.0.0/LSB-Core-generic/LSB-Core-generic/baselib-svctcp-create-3.html}

Documentation:@* @uref{https://www.kernel.org/doc/man-pages/online/pages/man3/svctcp_create.3.html,,man svctcp_create}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Minix 3.1.8, Cygwin 2.9, mingw, MSVC 14, Android 9.0.
@end itemize
