@node sys_errlist
@subsection @code{sys_errlist}
@findex sys_errlist

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This variable is missing on some platforms:
Minix 3.1.8, Mac OS X 10.5, IRIX 6.5, OSF/1 5.1, Cygwin, mingw, Interix 3.5, BeOS.
@end itemize
