@node wmempcpy
@subsection @code{wmempcpy}
@findex wmempcpy

Documentation:
@itemize
@item
@ifinfo
@ref{Copying Strings and Arrays,,Copying Strings and Arrays,libc},
@end ifinfo
@ifnotinfo
@url{https://www.gnu.org/software/libc/manual/html_node/Copying-Strings-and-Arrays.html},
@end ifnotinfo
@item
@uref{https://www.kernel.org/doc/man-pages/online/pages/man3/wmempcpy.3.html,,man wmempcpy}.
@end itemize

Gnulib module: wmempcpy

Portability problems fixed by Gnulib:
@itemize
@item
This function is missing on many non-glibc platforms:
macOS 11.1, FreeBSD 13.0, NetBSD 9.0, OpenBSD 6.7, Minix 3.1.8, AIX 5.1, HP-UX 11, IRIX 6.5, Solaris 11.4, Cygwin 2.9, mingw, MSVC 14, Android 5.1.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
On Windows and 32-bit AIX platforms, @code{wchar_t} is a 16-bit type and therefore cannot
accommodate all Unicode characters.
@end itemize
