@node xdr_enum
@subsection @code{xdr_enum}
@findex xdr_enum

Documentation:@* @uref{https://www.kernel.org/doc/man-pages/online/pages/man3/xdr_enum.3.html,,man xdr_enum}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Minix 3.1.8, Cygwin 1.7.4, mingw, MSVC 14, Android 9.0.
@end itemize
