@node xdr_opaque_auth
@subsection @code{xdr_opaque_auth}
@findex xdr_opaque_auth

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Minix 3.1.8, Cygwin, mingw, MSVC 9, BeOS.
@end itemize
