@node xdr_replymsg
@subsection @code{xdr_replymsg}
@findex xdr_replymsg

Documentation:@* @uref{https://www.kernel.org/doc/man-pages/online/pages/man3/xdr_replymsg.3.html,,man xdr_replymsg}

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This function is missing on some platforms:
Minix 3.1.8, Cygwin 2.9, mingw, MSVC 14, Android 9.0.
@end itemize
