@node a.out.h
@section @file{a.out.h}

Describes the structure of executables (and object files?) in the old
@code{a.out} format.

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This header file is missing on some platforms:
Mac OS X 10.5, Solaris 11 2011-11, mingw, MSVC 9, Interix 3.5, BeOS.
@item
This header file is useless because most executables and object files are
in ELF format on some platforms:
glibc 2.3.6, FreeBSD 6.0, NetBSD 5.0, OpenBSD 3.8.
@end itemize
