@node aliases.h
@section @file{aliases.h}

Defines the type @code{struct aliasent} and declares the functions
@code{setaliasent}, @code{endaliasent},
@code{getaliasent}, @code{getaliasent_r},
@code{getaliasbyname}, @code{getaliasbyname_r}.

Documentation:
@itemize
@item
@uref{https://www.kernel.org/doc/man-pages/online/pages/man3/setaliasent.3.html,,man setaliasent}.
@end itemize

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This header file is missing on all non-glibc platforms:
macOS 11.1, FreeBSD 13.0, NetBSD 9.0, OpenBSD 6.7, Minix 3.1.8, AIX 5.1, HP-UX 11, IRIX 6.5, Solaris 11.4, Cygwin, mingw, MSVC 14, Android 9.0.
@end itemize
