@node alloca.h
@section @file{alloca.h}

Declares the @code{alloca} function of function-like macro.

Documentation:
@itemize
@item
@ifinfo
@ref{Variable Size Automatic,,Automatic Storage with Variable Size,libc},
@end ifinfo
@ifnotinfo
@url{http://www.gnu.org/software/libc/manual/html_node/Variable-Size-Automatic.html},
@end ifnotinfo
@item
@uref{http://www.kernel.org/doc/man-pages/online/pages/man3/alloca.3.html,,man alloca}.
@end itemize

Gnulib module: alloca

Portability problems fixed by Gnulib:
@itemize
@item
This header file is missing on some platforms:
FreeBSD 6.0, NetBSD 5.0, OpenBSD 3.8, AIX 4.3.2, mingw, MSVC 9.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
