@node crypt.h
@section @file{crypt.h}

Defines the type @code{struct crypt_data} and declares the functions
@code{crypt}, @code{crypt_r},
@code{setkey}, @code{setkey_r},
@code{encrypt}, @code{encrypt_r}.

Documentation:
@itemize
@item
@ifinfo
@ref{crypt,,Encrypting Passwords,libc},
@ref{DES Encryption,,,libc},
@end ifinfo
@ifnotinfo
@url{https://www.gnu.org/software/libc/manual/html_node/crypt.html},
@url{https://www.gnu.org/software/libc/manual/html_node/DES-Encryption.html},
@end ifnotinfo
@item
@uref{https://www.kernel.org/doc/man-pages/online/pages/man3/crypt.3.html,,man crypt},
@uref{https://www.kernel.org/doc/man-pages/online/pages/man3/encrypt.3.html,,man encrypt}.
@end itemize

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This header file is missing on some platforms:
macOS 11.1, FreeBSD 13.0, NetBSD 9.0, OpenBSD 6.7, Minix 3.1.8, mingw, MSVC 14, Android 9.0.
@item
The functions @code{crypt}, @code{setkey}, @code{encrypt} are missing on some
platforms:
HP-UX 11.
@item
The type @code{struct crypt_data} and the functions @code{crypt_r},
@code{setkey_r}, @code{encrypt_r} are missing on some platforms:
IRIX 6.5, Solaris 11.4, Cygwin.
@end itemize
