@node error.h
@section @file{error.h}

Declares the functions @code{error}, @code{error_at_line} and the variables
@code{error_print_progname}, @code{error_message_count},
@code{error_one_per_line}.

Documentation:
@itemize
@item
@ifinfo
@ref{Error Messages,,,libc},
@end ifinfo
@ifnotinfo
@url{https://www.gnu.org/software/libc/manual/html_node/Error-Messages.html},
@end ifnotinfo
@item
@uref{https://www.kernel.org/doc/man-pages/online/pages/man3/error.3.html,,man error}.
@end itemize

Gnulib module: error

Portability problems fixed by Gnulib:
@itemize
@item
This header file is missing on many platforms:
macOS 11.1, FreeBSD 13.0, NetBSD 9.0, OpenBSD 6.7, Minix 3.1.8, AIX 5.1, HP-UX 11, IRIX 6.5, Solaris 11.4, Cygwin 1.7.9, mingw, MSVC 14.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
