@node ifaddrs.h
@section @file{ifaddrs.h}

Defines the type @code{struct ifaddrs} and declares the functions
@code{getifaddrs}, @code{freeifaddrs}.

Documentation:
@itemize
@item
@url{http://ecos.sourceware.org/docs-latest/ref/net-common-tcpip-manpages-getifaddrs.html}.
@end itemize

Gnulib module: ---

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This header file is missing on some platforms:
AIX 5.1, HP-UX 11, IRIX 6.5, OSF/1 5.1, Solaris 10, Cygwin, mingw, MSVC 9, Interix 3.5, BeOS.
@end itemize
