@node sys/random.h
@section @file{sys/random.h}

Declares the function @code{getrandom} and the flags for it.

Documentation:
@itemize
@item
@ifinfo
@ref{Unpredictable Bytes,,Generating Unpredictable Bytes,libc},
@end ifinfo
@ifnotinfo
@url{https://www.gnu.org/software/libc/manual/html_node/Unpredictable-Bytes.html},
@end ifnotinfo
@item
@uref{https://www.kernel.org/doc/man-pages/online/pages/man2/getrandom.2.html,,man getrandom}.
@end itemize

Gnulib module: sys_random

Portability problems fixed by Gnulib:
@itemize
@item
This header file is missing on some platforms:
glibc 2.24, NetBSD 5.0, OpenBSD 3.8, Minix 3.1.8, AIX 7.1, HP-UX 11.11, IRIX 6.5, Cygwin, mingw, MSVC 14.
@item
This header file is not self-contained on some platforms:
Mac OS X 10.13.
@item
This header file does not declare the @code{getrandom} function on some platforms:
Mac OS X 10.5, FreeBSD 11.0, HP-UX 11.31, Solaris 11.0.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
