@node utmp.h
@section @file{utmp.h}

Defines functions for login and logout (to a tty session) and for examining the
history of logins and logouts.

Documentation:
@itemize
@item
@ifinfo
@ref{Manipulating the Database,,Manipulating the User Accounting Database,libc},
@end ifinfo
@ifnotinfo
@url{https://www.gnu.org/software/libc/manual/html_node/Manipulating-the-Database.html},
@end ifnotinfo
@item
@uref{https://www.kernel.org/doc/man-pages/online/pages/man5/utmp.5.html,,man utmp}.
@end itemize

Gnulib module: utmp

Portability problems fixed by Gnulib:
@itemize
@item
This header file is missing on some platforms:
FreeBSD 13.0, mingw, MSVC 14.
@item
@code{<sys/types.h>} is a prerequisite of @code{<utmp.h>} on some platforms:
FreeBSD 8.0, OpenBSD 7.2.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
