@node arpa/inet.h
@section @file{arpa/inet.h}

POSIX specification: @url{http://www.opengroup.org/susv3xbd/arpa/inet.h.html}

Gnulib module: arpa_inet

Portability problems fixed by Gnulib:
@itemize
@item
This header file is missing on some platforms: mingw, BeOS.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
