@node locale.h
@section @file{locale.h}

POSIX specification: @url{http://www.opengroup.org/susv3xbd/locale.h.html}

Gnulib module: locale

Portability problems fixed by Gnulib:
@itemize
@item
The definition of @samp{LC_MESSAGES} is missing on some platforms:
mingw.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@end itemize
