@node search.h
@section @file{search.h}

POSIX specification: @url{http://www.opengroup.org/susv3xbd/search.h.html}

Gnulib module: search

Portability problems fixed by Gnulib:
@itemize
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
This header file is missing on some platforms:
BeOS.
@end itemize
