@node stdint.h
@section @file{stdint.h}

POSIX specification: @url{http://www.opengroup.org/susv3xbd/stdint.h.html}

Gnulib module: stdint

Portability problems fixed by Gnulib:
@itemize
@item
This header file is missing on some platforms:
OpenBSD 3.8, AIX 5.1, HP-UX 11, IRIX 6.5, OSF/1 5.1, Interix 3.5, BeOS.
@item
This header file is very incomplete on some platforms.
@item
The values of @code{SIG_ATOMIC_MIN} and @code{SIG_ATOMIC_MAX} are incorrect
on some platforms:
FreeBSD 6.2 / ia64.
@item
The value of @code{WINT_MAX} is incorrect on some platforms:
mingw.
@end itemize

Portability problems not fixed by Gnulib:
@itemize
@item
@code{@{uint,int@}_fast@{8,16,32,64@}_t} may not correspond to the fastest
types available on the system.
@item
Macros are used instead of typedefs.
@end itemize
